### ISSUE TITLE
[feature-request] Windows 7 Taskbar

### ISSUE THREAD

**Issue by Bluscream** [dremin/RetroBar#507] opened 2023-01-17 04:25 UTC
I love switching "OS" looks from time to time, just "upgraded" from WinXP to Vista. Would be nice if i could "upgrade" to windows 7 next :)

**Comment by 111ebobo** [comment] 2023-01-26 14:39
Developer said no

**Comment by DatGamerYoloYT** [comment] 2023-03-07 01:30
StartIsBack/StartAllBack may be useful to you as the superbar (the windows 7+ taskbar) is not what this was supposed to be for, it was supposed to be for the original taskbar (no pinning and no way to remove labels)

**Comment by dremin** [comment] 2023-04-28 00:00
Duplicate of #45

**Closed by dremin** 2023-04-28 00:00 UTC
