### ISSUE TITLE
Unable to resize the Quick Launch toolbar

### ISSUE THREAD

**Issue by abcxyz0123** [dremin/RetroBar#914] opened 2024-09-12 13:24 UTC
The Quick Launch toolbar cannot be resized.  It will display every item in the toolbar which causes loss of space on the taskbar if there are a lot of shortcuts in the toolbar.  I have made sure that the Retrobar taskbar was unlocked and also tested on 2 PC and was not able to resize the Quick Launch toolbar.  Is this by design, a limitation of Retrobar or a bug?

**Comment by GaryM99** [comment] 2024-09-13 07:12
It might help the developers or others if you included a screenshot of what you see, along with a description of exactly how you think the Quick Launch toolbar should resize to be smaller. You probably already know that you have full control over which icons appear there, but just in case you don't, here's the default location for the Quick Launch shortcuts...
`C:\Users\<user name>\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`

That's a standard Windows folder, so if you want to customize RetroBar's Quick Launch area without messing with the Windows configuration (and dodging program installers that add their program to the Quick Launch toolbar), you can also make your own custom folder of shortcuts and point RetroBar to it with the "Select location..." button in the RetroBar properties dialog. You can even hide the Quick Launch toolbar altogether. You have options to get extra space, but a more specific description of what you want would be more helpful.

**Comment by abcxyz0123** [comment] 2024-09-13 14:02
For example with my my Quick Launch Toolbar with ExplorerPatcher on Windows 11 I have the space size for 4 icons and there there is an overflow pop out that can be accessed by clicking the arrow to the right of the toolbar

![1Untitled](https://github.com/user-attachments/assets/7b0b878a-223e-470f-beec-4d688169aad8)

![2Untitled](https://github.com/user-attachments/assets/88a32c3f-85fd-4f4b-b6e7-058c70de92a4)

![Untitled](https://github.com/user-attachments/assets/52e21b1b-132a-4429-9265-076795626369)

- The Quick Launch Toolbar is supposed to allow you to drag and resize it and while Retrobar shows where you would click and drag to resize the toolbar is doesn't allow it
- This is how the Quick Launch Toolbar has works with ever version since it was introduced in Window 98 and ad a addon in 95 with IE4
- This behavior of it is normal and not a special feature.  Retrobar is the only Taskbar replacer that I have found that doesn't allow resizing of the Quick Launch toolbar and while I would very much like to use it unless it is possible that is deal breaker for me me size I have a lot shortcuts in my toolbar folder and it would use all the available space on my taskbar of I cannot resize it and have a overflow menu

**Comment by InsaneGal** [comment] 2024-09-13 16:18
Yeah, people have talked about this before and unfortunately it's never been a feature. Clicking on the time also brings up the notifications menu instead of the calender, which I thought was a bug at first but apparently not.

**Comment by abcxyz0123** [comment] 2024-09-13 20:02
A lot of people are angry that Microsoft did away with the Quick Launch Toolbar.  Many of us prefer not to pin apps for various reasons.  It is a lot less efficient to go to the Start Menu and the Quick Launch Toolbar was designed for efficient access to apps.  The reason that programs like Retrobar and ExplorerPatcher have come to rise is because of this.  Limiting the number of program in the toolbar defeats it purpose.  As I had stated earlier all other taskbar replacers replicate the function of Quick Launch Toolbar and allow you to resize it just as it did natively before Microsoft did away with in in Window 11 so it seems odd to me that only Retrobar had this limitation.  I do want to use Retrobar but this is deal breaking for me and I have that in future release this core function is added.

**Comment by abcxyz0123** [comment] 2024-09-25 02:05
> Yeah, people have talked about this before and unfortunately it's never been a feature. Clicking on the time also brings up the notifications menu instead of the calender, which I thought was a bug at first but apparently not.

I guess this should be considered a feature request then.  For me unless this feature is added it is a deal breaker and that is unfortunate since Retrobar as free app has a lot of great features for which I would choose it over other similar apps if there wasn't this limitation on the core function that I most want such a product for.

**Comment by dremin** [comment] 2024-11-29 22:44
Closing as duplicate of #377.

**Closed by dremin** 2024-11-29 22:44 UTC

**Comment by shoulders** [comment] 2025-04-13 17:45
I know this has been closed but it seems the best place to post.

I also would the ability to resize the quick launch area so i can force them on to 2 lines and maximise my real estate.

Other people possible want them hidden when the quick lauch area is too small, similar to how windows use to do it.

I think this feature will be much needed now that Windows 11 24H2 has remove quick launch altogether.

Perhaps this could be looked at again.

Thanks
