### ISSUE TITLE
Explorer Crashing and Restarting on 24H2

### ISSUE THREAD

**Issue by manaphychu** [dremin/RetroBar#938] opened 2024-10-30 19:59 UTC
Hey, Can you try fixing this issue where Explorer Restarts on its own in an infinite loop after I restarted Windows Explorer?

I was making my Windows 11 24H2 Installation look like XP, but as it turns out, Retrobar crashes the Windows Explorer shell constantly when on 24H2, any help here?

**Comment by dremin** [comment] 2024-11-21 07:01
Closing as duplicate of #457 (which will be fixed in the next version).

**Closed by dremin** 2024-11-21 07:01 UTC
