### ISSUE TITLE
Auto-hide RetroBar

### ISSUE THREAD

**Issue by dhruvErryDrew** [dremin/RetroBar#319] opened 2022-04-08 19:37 UTC
I don't know how this feature hasn't been incorporated yet, but the lack of the ability to auto-hide the taskbar renders RetroBar useless for me. 

(By auto-hide I'm referring to the built-in Windows feature to hide the taskbar unless the mouse is hovered around and on it, usually toward the bottom of the screen.)

Would really appreciate this.

**Comment by dremin** [comment] 2022-07-19 02:20
Duplicate of #77

**Closed by dremin** 2022-07-19 02:20 UTC

**Comment by yereverluvinunclebert** [comment] 2023-05-02 21:36
Bloody strange to close it. It is a BASIC feature of a dock/taskbar. It is absolutely required, If not planned then it shows a failure of imagination or understanding. I mean how difficult can it be? Set the opacity of the entire form to 0. 

    currentOpacity = Opacity
    Call SetWindowLong(FireCallMain.hwnd, GWL_EXSTYLE, GetWindowLong(FireCallMain.hwnd, GWL_EXSTYLE) Or WS_EX_LAYERED)
    Call SetLayeredWindowAttributes(FireCallMain.hwnd, RGB(255, 0, 255), Opacity, LWA_ALPHA Or LWA_COLORKEY)

**Comment by dremin** [comment] 2023-05-03 00:13
@yereverluvinunclebert "Not planned" in this case means this specific issue is a duplicate. GitHub's language here could certainly be better. I do intend to implement auto-hide in #77.

**Comment by yereverluvinunclebert** [comment] 2023-05-03 10:27
Crikey! Apologies then. That is a silly feature of github. It might be wise to add a comment in this case. Good to know this is being planned. I will watch #77. Good luck.
