### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by holaimscott** [dremin/RetroBar#280] opened 2022-03-17 20:07 UTC
Great project :) It would be amazing if you could consider making this also in an ARM64 native support, since it would be nice to add to my ARM PC device without having to emulate it via emu layer.

**Comment by xoascf** [comment] 2022-03-17 20:25
Please could you check if this build works for you on ARM?

[RetroBar_AnyCPU.zip](https://github.com/dremin/RetroBar/files/8291514/RetroBar_AnyCPU.zip)

**Comment by holaimscott** [comment] 2022-03-18 00:57
Thank you so much for this!! Let me test it shortly and will update you 👍  I appreciate your response

**Comment by holaimscott** [comment] 2022-03-18 02:00
Thank you so much, [it seems to work really week!](https://drive.google.com/file/d/1iMvA0TYtMJW3qlbWxjea319LZI87xvdJ/view?usp=sharing)

Other ARM folks will appreciate this too :)

**Comment by holaimscott** [comment] 2022-03-29 21:58
> 



> Please could you check if this build works for you on ARM?
> 
> [RetroBar_AnyCPU.zip](https://github.com/dremin/RetroBar/files/8291514/RetroBar_AnyCPU.zip)

Again, thank you so much for this, the app works perfectly! I do want to ask if the ARM build will be included in the official releases, or if this is the only ARM version that will be out (since I want to see if updates would apply to this build)?

So far our ARM community has tested it and love it a lot!

**Comment by dremin** [comment] 2022-03-29 22:11
Right now that is the only ARM build, but is my intent to have official ARM builds available for the next release--my ARM machine is on the delivery truck right now :)

**Comment by holaimscott** [comment] 2022-03-29 22:13
> Right now that is the only ARM build, but is my intent to have official ARM builds available for the next release--my ARM machine is on the delivery truck right now :)

Gotcha, that means alot to hear this... just wanted to say thank you so much to all of you :)

**Comment by dremin** [comment] 2022-04-03 05:57
@holaimscott Here is a new ARM64 build if you would like to try: [RetroBar.zip](https://github.com/dremin/RetroBar/files/8403893/RetroBar.zip)

On my system the old one actually showed as x64 in Task Manager, this one shows correctly as ARM64.

**Comment by holaimscott** [comment] 2022-04-03 21:28
Thank you so much! Seems to work perfectly (tested by one user that also has an ARM device)

https://user-images.githubusercontent.com/101499382/161449331-73e948e0-845d-448d-bdbd-eb0578230a85.mp4

**Comment by dremin** [comment] 2022-07-19 02:15
Closing as duplicate of #66 which is part of the upcoming release.

**Closed by dremin** 2022-07-19 02:15 UTC
