### ISSUE TITLE
could we have a show desktop button in the bottom right

### ISSUE THREAD

**Issue by Tommy2678** [dremin/RetroBar#316] opened 2022-04-06 17:56 UTC
have it be a toggleable for the people who don't prefer it, but i'm really missing it

**Comment by zigafide** [comment] 2022-04-06 18:13
Windows key + M does the same thing, if this never gets added

**Comment by exalye** [comment] 2022-04-07 00:43
create shortcut with adress C:\Windows\explorer.exe shell:::{3080F90D-D7AD-11D9-BD98-0000947B0257} and and it to your Quick Launch folder.

**Comment by xoascf** [comment] 2022-04-08 05:27
Duplicate of #84

**Comment by TommyHeavenLy6** [comment] 2022-04-11 20:31
Not for bottom right but it could be add to right click cuz all Windows versions had that if i remember correct.

**Comment by dremin** [comment] 2022-07-19 02:20
Duplicate of #84

**Closed by dremin** 2022-07-19 02:20 UTC
Labels: duplicate
