### ISSUE TITLE
Request to introduce an option to scale the taskbar only

### ISSUE THREAD

**Issue by Zerberuss** [dremin/RetroBar#566] opened 2023-05-01 19:16 UTC
The taskbar on my uwqhd screen is too small, and I changed the scaling of windows to 125%, which made it perfect. However, this scaling also affects all other programs, making them appear larger than I want them to. I believe it would be helpful if there was an option to scale the taskbar only.

When the scaling is set to 100%, most icons on the taskbar are too small to click comfortably. Therefore, having the ability to adjust the scaling of the taskbar separately from the rest of the desktop would improve user experience.

Thank you for considering my request.

**Comment by dremin** [comment] 2023-05-05 23:30
Duplicate of #480 where I will be addressing this.

**Closed by dremin** 2023-05-05 23:30 UTC
