### ISSUE TITLE
[Request] Currently no "Show Desktop" on the edge 

### ISSUE THREAD

**Issue by SlitEye** [dremin/RetroBar#406] opened 2022-08-03 15:22 UTC
Hello Together, 

currently RetroBar has no "Show Desktop" button like Windows 10/11:
![2022-08-03_17h05_11](https://user-images.githubusercontent.com/24313436/182645648-b9506efd-938b-461c-b3a8-0055a8fc65e6.png)

It would be nice if this was available for the older themes or for all themes and that it can be optionally activated/deactivated.

**Comment by xoascf** [comment] 2022-08-03 21:54
Duplicate of #84

**Closed by xoascf** 2022-08-03 21:54 UTC
