### ISSUE TITLE
Suggestion: toolbar support

### ISSUE THREAD

**Issue by CrazyFrogEpic** [dremin/RetroBar#244] opened 2022-02-15 12:33 UTC
i.e. WMP9 mini-mode
![image](https://user-images.githubusercontent.com/77507284/154062797-695129e2-fc35-4752-bbe9-5b159f784105.png)

**Comment by dremin** [comment] 2022-07-19 02:12
Duplicate of #42

**Closed by dremin** 2022-07-19 02:12 UTC
