### ISSUE TITLE
Add option to scale the size of the taskbar without having to change windows scale

### ISSUE THREAD

**Issue by deva0000** [dremin/RetroBar#502] opened 2023-01-08 21:33 UTC
On my display the task looks miniscule, smaller than the default w10 taskbar. When I set windows scale to 125% the taskbar looks great, but everything else is horrible. If the taskbar already can scale with windows, its possible for a option to change its size without having to do it?

**Comment by Nozza76** [comment] 2023-02-08 20:27
I'll second this. On my display the start menu looks hilariously small, and the display scaling doesn't even help. Being able to change the size of the taskbar would be a huge plus for me. As a new user, not seeing this option available was extremely confusing to me.

**Comment by dremin** [comment] 2023-05-05 23:30
Duplicate of #480 where I will be addressing this.

**Closed by dremin** 2023-05-05 23:30 UTC
