### ISSUE TITLE
maximise window doesn't work correct 

### ISSUE THREAD

**Issue by frox77** [dremin/RetroBar#561] opened 2023-04-23 14:40 UTC
When Retrobar is started then can not Maximise window. Stay a stripe. W11, v.1.11.15

![retrobar](https://user-images.githubusercontent.com/131601278/233845774-cee49f22-f8d8-4b33-bab2-172c2df6f8f4.jpg)

**Comment by tony-aw** [comment] 2023-04-23 20:37
I have the same issue. The problem is essentially that RetroBar is thinner than Windows 11 taskbar, hence fullscreen windows only go down until they reach the point of the original Windows 11 taskbar. Disabling/closing RetroBar and then re-enabling RetroBar solves the issue for me. But it is indeed annoying I have to disable and then enable RetroBar multiple times.

**Comment by frox77** [comment] 2023-04-24 06:30
For me re-enabling RetroBar doesn't solve the issue, and the stripe is also wider than remaining space from W11 taskbar. Sometimes it runs fine, but sometimes.

**Comment by buuuix** [comment] 2023-05-01 09:04
what works for me is switching between the bar positions, ez fix its just annoying to do all the time

**Comment by dremin** [comment] 2023-05-05 23:29
Recent updates have impacted RetroBar's ability to hide the default Windows taskbar. Before starting RetroBar, it is recommended to open Windows Settings > Personalization > Taskbar, select "Taskbar behaviors", then enable "Automatically hide the taskbar."

**Comment by frox77** [comment] 2023-05-06 12:16
> Recent updates have impacted RetroBar's ability to hide the default Windows taskbar. Before starting RetroBar, it is recommended to open Windows Settings > Personalization > Taskbar, select "Taskbar behaviors", then enable "Automatically hide the taskbar."

Thanks Dremin, your hint fixes my problem 👍

**Closed** 2023-08-29 19:08 UTC
