### ISSUE TITLE
RetroBar flashing glitch

### ISSUE THREAD

**Issue by TigercatX** [dremin/RetroBar#813] opened 2024-04-27 08:01 UTC
Hello,
I have been using retrobar since months because I find old Windows application bar more "clean" and nice to see. Unfortunately, I have to report this glitch, which seems to be related with Retrobar.
I can't define what is causing it, but sometimes my entire wallpaper starts to "flash" from black to it's original image, and it loops like this. At the beginning, I thought that it was an Windows 11's issue, but then I've figured out that closing Retrobar was enough to stop this. The chances of this bug to happen are low, but when it happens it's really annoying as it becomes difficult to interact with my computer. It's literally impossible to close the application as the "flashing" or the "refreshing" of the application doesn't let me right click on it to turn off the process.

Thank you for reading my issue, have a good day

**Comment by dremin** [comment] 2024-11-29 21:50
Closing as duplicate of #457 which is fixed in the next release.

**Closed by dremin** 2024-11-29 21:50 UTC
