### ISSUE TITLE
QuickLaunch hotkeys dont work. 

### ISSUE THREAD

**Issue by AJolly** [dremin/RetroBar#882] opened 2024-07-04 22:15 UTC
The hotkeys for quicklaunch shortcuts dont seem to work  win+1, win+2, etc.

**Comment by 111ebobo** [comment] 2024-07-05 12:51
It's not a bug, they're wasn't working in that versions because quick launch is just a toolbar with a bunch of shortcuts

**Comment by dremin** [comment] 2024-11-29 22:42
Closing as duplicate of #70.

**Closed by dremin** 2024-11-29 22:42 UTC

**Comment by xoascf** [comment] 2025-05-07 00:40
This feature is live: you have to enable it first in the **Advanced** tab of **RetroBar Properties**, and then press the win+number hotkeys to launch Quick Launch items or switch tasks.
