### ISSUE TITLE
[Bug report] explorer.exe keeps crashing at windows 11

### ISSUE THREAD

**Issue by dhlrunner** [dremin/RetroBar#476] opened 2022-11-24 01:32 UTC
OS : Windows 11 Pro for Workstations 22H2 build 22621.819

Problems : If i restart explorer with Retrobar enabled, explorer keeps crashing.

[![Watch the video]()](https://user-images.githubusercontent.com/37791084/203673918-bd859a2e-0365-428b-b633-a0b37bb7d126.mp4)

This is the event log after explorer.exe crashed.
![image](https://user-images.githubusercontent.com/37791084/203673829-c0f0cb32-5683-4362-aa3d-62f8cdab5524.png)

If there is any other information I need to provide, please let me know. 
Thank you for making a great application.

**Comment by Dawid8plc** [comment] 2022-11-29 11:55
Im experiencing the same issue

**Comment by justlittlesummer** [comment] 2022-12-15 08:51
the same issue. its a fatal bug :(

**Comment by dremin** [comment] 2024-11-21 07:01
Closing as duplicate of #457 (which will be fixed in the next version).

**Closed by dremin** 2024-11-21 07:01 UTC
