### ISSUE TITLE
1.10 does not work with multiple monitors

### ISSUE THREAD

**Issue by Vexzilla1970** [dremin/RetroBar#456] opened 2022-10-31 09:44 UTC
I check the box for multiple monitors and it crashes the program and can not be recovered or even copied over with a different version.

**Comment by Vexzilla1970** [comment] 2022-11-07 07:47
THe program starts but immediately crashes. I cannot access the settings to turn multiple monitors off.. The only version that now works is 1.8. I dare not check multiple monitors again for fear of crashing it also...

**Comment by dremin** [comment] 2022-11-08 04:53
If you close RetroBar and delete the `%localappdata%\RetroBar` folder that should reset the settings and allow you to use the newer version. I'd like to troubleshoot the crash some more to try and fix the issue you're running into. When it crashes, do you see any error messages? Does an error appear in the Windows application event log?

**Comment by Vexzilla1970** [comment] 2022-11-08 06:22
No error messages, yes, it appears in the event log...

**Comment by dremin** [comment] 2022-11-14 06:20
@Vexzilla1970 What does it say in the event log?

**Comment by Vexzilla1970** [comment] 2022-11-14 06:47
Faulting application name: RetroBar.exe, version: 1.10.2.38481, time stamp: 0x62cf0990
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2130, time stamp: 0xb0fac6c9
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x340
Faulting application start time: 0x01d8f277062c7a35
Faulting application path: C:\Program Files\RetroBar\RetroBar.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: c91835c8-5cff-415f-9580-c9c076164377
Faulting package full name: 
Faulting package-relative application ID: 


Hope this is what you need...

**Comment by dremin** [comment] 2022-11-19 05:08
Thanks @Vexzilla1970, that's exactly what I needed. This is actually a problem I've encountered once but a reboot fixed it so I wasn't able to investigate further. Basically, the app is getting into a loop trying to place the taskbar in the correct position, but Explorer is moving it back.

**Comment by Vexzilla1970** [comment] 2022-11-20 15:32
Yep, it works now... sadly, i have now another problem.... with low resolution full screen games.... retrobar does not like them at all... it freaks out when I open the game and when i close the game it gets stuck trying to position itself on the monitors... I have attached the log files that I believe are associated with this issue...
[Logs.zip](https://github.com/dremin/RetroBar/files/10050045/Logs.zip)

**Comment by kuwii** [comment] 2023-01-06 03:37
@dremin FYI, I can stably repro this when my 2 monitors have different scales (one is 100% and another is 150%).

![image](https://user-images.githubusercontent.com/10705175/210924931-a15505c9-f86e-4fa8-b5c8-1a0da9ea8c72.png)

**Comment by aahei** [comment] 2023-01-27 06:53
> @dremin FYI, I can stably repro this when my 2 monitors have different scales (one is 100% and another is 150%).
> 
> ![image](https://user-images.githubusercontent.com/10705175/210924931-a15505c9-f86e-4fa8-b5c8-1a0da9ea8c72.png)

Second.

**Comment by dremin** [comment] 2023-02-03 06:42
Thanks, I can reproduce this reliably now and am working on a fix.

**Comment by dremin** [comment] 2023-02-04 05:46
Could you please test this build and let me know if it works as expected now? I believe I have fixed the issue. It's an x64 build, let me know if you need a different arch.
[RetroBar.zip](https://github.com/dremin/RetroBar/files/10607815/RetroBar.zip)

**Comment by kuwii** [comment] 2023-02-04 12:08
> Could you please test this build and let me know if it works as expected now? I believe I have fixed the issue. It's an x64 build, let me know if you need a different arch. [RetroBar.zip](https://github.com/dremin/RetroBar/files/10607815/RetroBar.zip)

Thanks for the fix. It works for me.

**Comment by dremin** [comment] 2023-03-24 04:04
@ThePunisher69 You are correct, there are some issues that I have been working on in this area. I'll update this space when I have a new test build ready with those fixes.

**Comment by dremin** [comment] 2023-05-07 23:06
The confirmed fix is available in the latest release.

**Closed by dremin** 2023-05-07 23:06 UTC
