### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by Frapoo** [dremin/RetroBar#39] opened 2021-07-12 15:13 UTC
![125190311-0484ee80-e26f-11eb-901d-7573de4d2ebc~3](https://user-images.githubusercontent.com/61443778/125312101-902d7680-e366-11eb-810e-0f5afd1229d2.png)

Cannot drag and drop and rearrange these icons/shortcuts.

**Comment by Frapoo** [comment] 2021-07-12 15:20
May you also check tray icons too, please!

**Comment by ThePillenwerfer** [comment] 2021-08-29 12:19
That's a function I'd like to see too.

**Comment by dremin** [comment] 2022-01-12 05:06
Closing as duplicate of #19, which should be fixed in the next release.

**Closed by dremin** 2022-01-12 05:06 UTC
