### ISSUE TITLE
is there any way on windoes 10?

### ISSUE THREAD

**Issue by bdog74** [dremin/RetroBar#56] opened 2021-08-29 01:14 UTC
to make the taskbar bigger and the icons?

**Comment by DavidXanatos** [comment] 2021-09-12 14:59
yea that would be cool,
its time for retro bar to include win 7 style in its retro arsenale

**Comment by dremin** [comment] 2022-03-10 05:23
Closing as duplicate of #14

**Closed by dremin** 2022-03-10 05:23 UTC
