### ISSUE TITLE
System Tray Icons (feature request)

### ISSUE THREAD

**Issue by TheDolphinSlayer** [dremin/RetroBar#67] opened 2021-08-30 16:29 UTC
Using RetroBar for the XP look, I usually use the programs "3RVX" and "NetAnimate" normally for my Windows Xp look. The option to choose which system icons can appear on the system tray in nonexistent.  Those two programs above are used to restore the Windows XP Volume+Network icons as well as some functionality. For an example, 3RVX brings back the classic volume slider, which has skins from windows 9k-XP. I can have those programs there, but the "actual" volcontrol and network are there.
(images+video from "winclassic.boards" by Clasurol/Jackal showing 3RVX in action.)

https://www.youtube.com/watch?v=-NloPGWgUnU&feature=emb_title

![image](https://user-images.githubusercontent.com/73983610/131372197-7b723791-3387-48d3-9e47-4c68ca7e5645.png)

**Comment by dremin** [comment] 2021-09-24 23:39
Duplicate of #47

**Closed by dremin** 2021-09-24 23:39 UTC
