### ISSUE TITLE
Longhorn Aero Theme

### ISSUE THREAD

**Issue by TheDolphinSlayer** [dremin/RetroBar#352] opened 2022-06-13 21:37 UTC
THIS SERIOUSLY LOOKS AMAZING!

Does that mean Vista Aero and Windows 7 aero soon? (Hopefully with the Vista/Windows 7 Jumplist, and customizable notification systray : D

**Comment by dremin** [comment] 2022-06-25 18:55
Glad you like it! I am working on a Vista Aero theme at the moment.

**Comment by XTMYTYT** [comment] 2022-06-28 17:09
> Glad you like it! I am working on a Vista Aero theme at the moment.

are you also gonna leak a picture of the vista aero theme or u can make also the basic theme

**Comment by WF4123** [comment] 2022-07-01 20:44
> Glad you like it! I am working on a Vista Aero theme at the moment.

Finally. I cannot wait for a moment.

**Comment by dremin** [comment] 2022-07-13 04:02
Closing as duplicate of #15 (which the PR is linked to).

**Closed by dremin** 2022-07-13 04:02 UTC
