### ISSUE TITLE
Vista basic theme pls

### ISSUE THREAD

**Issue by Pixel556** [dremin/RetroBar#326] opened 2022-04-14 04:13 UTC
Add vista basic theme please

**Comment by Lianaja32** [comment] 2022-04-14 07:13
Some people have the same request, and i have the same idea.

**Comment by MasterSlenderTR** [comment] 2022-04-21 08:10
Yeah, it'd be nice.

**Comment by Pixel556** [comment] 2022-04-21 16:58
Yeah.

**Comment by Pixel556** [comment] 2022-04-21 16:58
We're so lucky! 95 issues!

**Comment by dremin** [comment] 2022-07-13 04:02
Closing as duplicate of #15 (which the PR is linked to).

**Closed by dremin** 2022-07-13 04:02 UTC
