### ISSUE TITLE
[Feature Request] Allow users to use [Win] + [Number key] to open applications in Quick Launch

### ISSUE THREAD

**Issue by khalleu** [dremin/RetroBar#564] opened 2023-04-27 20:31 UTC
Hey! I'm loving this little piece of software so far, but I wish I could open my web browser with [Win] + 1!

By default, you can press [Win] + [Number key] in order to open the application in that spot on the taskbar.

Could we get this feature in RetroBar?

**Comment by dremin** [comment] 2023-04-28 00:06
Duplicate of #70 
There's an explanation in that bug of why it doesn't work. Unfortunately Explorer has the key combos registered, so we can't do anything about it (without loading a hook into Explorer)

**Closed by dremin** 2023-04-28 00:06 UTC

**Comment by xoascf** [comment] 2025-05-07 00:37
RetroBar now offers this feature in its latest release - go to **RetroBar Properties** > **Advanced tab** to change and apply this behavior first, then press [Win] + [Number key] to switch tasks or open Quick Launch items.
