### ISSUE TITLE
Request: Windows Vista aero theme and default non aero

### ISSUE THREAD

**Issue by 111ebobo** [dremin/RetroBar#328] opened 2022-04-23 08:09 UTC

**Comment by MLXProjects** [comment] 2022-04-27 21:39
That's not exactly retro, at least not from the graphical point of view (when graphics composition came into Windows).
Anyway, I would love to use transparency into themes :P
I don't seem the only one thinking about making RetroBar something morepowerful than a "retro taskbar mod" for Windows.

**Comment by 111ebobo** [comment] 2022-04-28 06:52
> That's not exactly retro, at least not from the graphical point of view (when graphics composition came into Windows).
> Anyway, I would love to use transparency into themes :P
> I don't seem the only one thinking about making RetroBar something morepowerful than a "retro taskbar mod" for Windows.

I think if we have a Vista classic theme, why not have a normal theme because Vista's design for example for me is the best so why not add it?

**Comment by MLXProjects** [comment] 2022-04-28 14:26
> > That's not exactly retro, at least not from the graphical point of view (when graphics composition came into Windows).
> > Anyway, I would love to use transparency into themes :P
> > I don't seem the only one thinking about making RetroBar something morepowerful than a "retro taskbar mod" for Windows.
> 
> I think if we have a Vista classic theme, why not have a normal theme because Vista's design for example for me is the best so why not add it?

at least regarding transparency, I think that RetroBar aims to give the classic/legacy look&feel instead of being just a taskbar theming software.
Anyway, I've just noticed that Vista is over 15 years old, so it might be considered "retro" as the Aero theme was deprecated starting with 8.
If I ever get retrobar to build with vs2019 (throws unsupported .net 6.0 errors), I would love to make that possible.

**Comment by dremin** [comment] 2022-07-13 04:02
Closing as duplicate of #15 (which the PR is linked to).

**Closed by dremin** 2022-07-13 04:02 UTC
