### ISSUE TITLE
Windows 7 Theme

### ISSUE THREAD

**Issue by SeventySev3n** [dremin/RetroBar#785] opened 2024-04-02 13:57 UTC
Not sure if it's too soon, but I feel like Windows 7 is retro enough to get it's own theme now, hahaha.

Would love to switch back to the Windows 7 taskbar, I have a lot of nostalgia for it 💜.

**Comment by 111ebobo** [comment] 2024-04-02 22:30
It has a different technology and also try using startisback

**Comment by LilacMonarch** [comment] 2024-04-05 04:36
I use OpenShell with the 7 start button and taskbar texture, it's not perfect but it looks pretty close

**Comment by zovcoder** [comment] 2024-04-06 17:59
> I use OpenShell with the 7 start button and taskbar texture, it's not perfect but it looks pretty close

can you tell in detail how you did it?

**Comment by LilacMonarch** [comment] 2024-04-17 06:22
@zovcoder I did it like this

Start button:
![filecf97](https://github.com/dremin/RetroBar/assets/26831349/a2f7b8be-09b3-425f-aa01-5a45dcde18cf)

Taskbar:
![Win720Taskbar20Reflection20for20opacity204020qty202](https://github.com/dremin/RetroBar/assets/26831349/0df8fbf5-1eac-4ccb-8e18-787d0fd39cf8)
Go to the Taskbar tab in OpenShell settings

Taskbar look: Glass
Taskbar opacity: 75
Taskbar color: [whatever color you want]
Taskbar text color: FFFFFF
Taskbar texture: [image above]
Horizontal stretching: Tile
Vertical stretching: Stretch

**Comment by dremin** [comment] 2024-07-17 00:49
Duplicate of #45

**Closed by dremin** 2024-07-17 00:49 UTC
