### ISSUE TITLE
Problems with switching between desktops

### ISSUE THREAD

**Issue by lauratorrents0202** [dremin/RetroBar#596] opened 2023-06-06 23:27 UTC
Hi! I'm someone who uses more that one desktop all the time, and when I switch desktops, the tabs from the last desktop still remain on the taskbar. If it is something like Chrome, which is mostly always open in all the desktops, as soon as I open the tabs from that desktop, the leftover ones disappear. But if it's something that is only open in one desktop, then I can't make it disappear from the taskbar in the rest of the desktops, so there will always be, say, a Word document in there, even if there are none on the current desktop.

Bringing this up because I love RetroBar! This being solved would be amazing. Also sorry if anyone else brought this up before and I didn't notice.

Thank you!

**Comment by dremin** [comment] 2024-12-02 01:07
Closing as duplicate of #131, which I have a fix coming for.

**Closed by dremin** 2024-12-02 01:07 UTC
