### ISSUE TITLE
(Suggestion) grouping

### ISSUE THREAD

**Issue by rikardo17** [dremin/RetroBar#593] opened 2023-05-31 05:25 UTC
hello good morning, would it be possible to put in groups as before? for example chrome in a group, explorer in another group, I would love to have this option until each separator was smaller, here's the tip, thanks

**Comment by 111ebobo** [comment] 2023-05-31 06:48
I think it will be good if it will be like in pre windows 7 taskbars

**Comment by BobbyMcJefferson** [comment] 2023-06-03 14:51
I agree this would be very useful. I always have a lot of stuff open and without grouping it becomes a real mess. Maybe an option to set the minimum amount of windows of the same type before they should be grouped?

Additionally, it would be nice if you could peek at each window just by hovering over it.

**Comment by xoascf** [comment] 2023-06-05 19:15
Duplicate of #119

**Closed by xoascf** 2023-06-05 19:15 UTC
