### ISSUE TITLE
Usability: Show Desktop Button on the Bottom Right corner should be Borderless

### ISSUE THREAD

**Issue by zxfghwr** [dremin/RetroBar#680] opened 2023-09-10 21:39 UTC
Currently, you need to position your mouse a few pixels above and to the left of the actual corner to press the Show Desktop button. 

If you have used the show desktop button (the one  in the bottom right) in Windows before, you will know they are borderless and extend all the way to the corner so you don't need to be a precision gamer to press the button every single time. 

![Screenshot 2023-09-11 073742](https://github.com/dremin/RetroBar/assets/24627649/f806bd5b-ac8d-4551-bead-0297d33654e3)

**Comment by xoascf** [comment] 2023-09-12 14:56
Oddly enough, I don't remember having this issue when I merged #169, so it's probably a regression due to a violation of Fitts' law.

**Comment by 111ebobo** [comment] 2023-09-12 21:07
> Currently, you need to position your mouse a few pixels above and to the left of the actual corner to press the Show Desktop button. 
> 
> If you have used the show desktop button (the one  in the bottom right) in Windows before, you will know they are borderless and extend all the way to the corner so you don't need to be a precision gamer to press the button every single time. 
> 
> ![Screenshot 2023-09-11 073742](https://github.com/dremin/RetroBar/assets/24627649/f806bd5b-ac8d-4551-bead-0297d33654e3)
> 

In these versions of windows taskbar there should not be the "show desktop" button

**Closed** 2024-02-27 08:59 UTC
