### ISSUE TITLE
Feature request - Start button on multiple monitors

### ISSUE THREAD

**Issue by sharicov** [dremin/RetroBar#836] opened 2024-05-13 07:41 UTC
When using RetroBar on multiple displays with Show on multiple displays option checked, start button is only shown on main monitor, please add button on other monitors as well (win key already opens start menu properly on active monitor).
Thanks in advance!

**Comment by wardhale** [comment] 2024-05-14 10:59
I'm quite the opposite. I'd like to remove the quick-launch toolbar and just have the buttons/tabs on each monitor... and the start and toolbar on the main monitor... but options for all that would be cool.

**Comment by dremin** [comment] 2024-11-29 22:16
Closing as duplicate of #158.

**Closed by dremin** 2024-11-29 22:16 UTC
