### ISSUE TITLE
Add Language Icons to Taskbar / Language Icons missing when switching to specific language

### ISSUE THREAD

**Issue by Krunchy0920** [dremin/RetroBar#521] opened 2023-02-10 04:10 UTC
Hi! I use RetroBar and it's one of my favorite apps in general. I was wondering if you can add language icons to the taskbar? when switching to something like Japanese, the icons don't show up and it's tedious having to exit RetroBar and switching properly on the OG taskbar..

1st Pic (OG Taskbar, Startisback++ on)
![image](https://user-images.githubusercontent.com/81315028/217998606-3c82a9fe-7cb5-42ac-a9c1-cb04577a168e.png)

2nd Pic (RetroBar)
![image](https://user-images.githubusercontent.com/81315028/217998671-d05d385c-0708-405c-9fef-077875e44666.png)

**Comment by dremin** [comment] 2023-04-28 00:02
Duplicate of #68

**Closed by dremin** 2023-04-28 00:02 UTC
