### ISSUE TITLE
clock and system icons issue

### ISSUE THREAD

**Issue by ssp88** [dremin/RetroBar#684] opened 2023-09-12 18:20 UTC
in the Windows settings, I hid the display of Internet and sound system icons, as well as the microphone, but they still appear in the retrobar and cannot be removed. also the distance between the icons and the clock is too big
![issue](https://github.com/dremin/RetroBar/assets/141490640/227c4ec6-78c4-4fab-a978-a5f64362a568)

**Comment by sexzyura** [comment] 2023-10-17 08:55
you didn't understand the question. I want these icons to disappear altogether, and not hide somewhere in the tray

**Comment by dremin** [comment] 2024-04-28 08:19
Closing as a duplicate of #338 which I am working on.

**Closed by dremin** 2024-04-28 08:19 UTC
