### ISSUE TITLE
"click here to begin" tooltip randomly appears, not detrimental but annoying

### ISSUE THREAD

**Issue by samiscoolest** [dremin/RetroBar#455] opened 2022-10-31 01:30 UTC
sometimes when clicking off retrobar the "click here to begin" start menu tooltip will suddenly appear, and never go away until retrobar is clicked on again.  this is very annoying and if the tooltip could just be disabled altogether itd be nice
![image](https://user-images.githubusercontent.com/57376107/198913593-8ae4d6d6-d3a8-4d87-8e4f-e22cc325d93a.png)

**Comment by Carl-Robert** [comment] 2022-11-05 08:58
Same issue here. Increasingly annoying, because the tooltip is randomly on top of games and video-players too. Related to this issue is that sometimes the taskbar is also on top of fullscreen video-players until clicked/otherwise switching focus on the video-player. So there might be underlying focus issues.

How could I help debugging this issue? Disabling the tooltip could be a temporary solution meanwhile.

**Comment by samiscoolest** [comment] 2023-11-05 03:26
it has been a year and this is still annoying the crap out of me

**Comment by samiscoolest** [comment] 2023-11-05 03:26
fix it

**Comment by xoascf** [comment] 2023-11-07 19:08
> fix it

Not sure how to trigger it, it just doesn't happen to me, so I have no idea how to fix it other than removing the tooltip from the Start button.

**Comment by dremin** [comment] 2023-11-08 00:15
I can reproduce; I have logic to fix this with auto-hide but not without auto-hide. I need to add some code to trigger that logic when the RetroBar window loses focus.

**Comment by dremin** [comment] 2023-11-08 00:16
> fix it

It would be super helpful if you could confirm that the issue does not occur with auto-hide enabled, so that I make sure I am doing the right fix :)

**Comment by dremin** [comment] 2023-11-11 19:57
The issue should be fixed in [this test build](https://github.com/dremin/RetroBar/suites/18109417606/artifacts/1043875550) if you'd like to confirm. Thanks!

**Comment by dremin** [comment] 2023-11-12 05:29
Great, thanks for testing @Carl-Robert!

**Closed** 2024-04-30 05:39 UTC

**Comment by xoascf** [comment] 2024-04-30 06:14
For some reason, it never happened to me, but recently when I turned on the laptop after hibernation, the Show Desktop tooltip randomly popped up.
