### ISSUE TITLE
Increase size of taskbar windows

### ISSUE THREAD

**Issue by dhruvErryDrew** [dremin/RetroBar#320] opened 2022-04-08 19:40 UTC
Can we have the option to increase the size (more specifically, the height) of the windows in the taskbar? I'm talking about the clickable rectangles for each open window.

**Comment by holaimscott** [comment] 2022-06-07 14:41
This would be a cool feature to add! I second this :)

**Comment by dremin** [comment] 2022-07-19 02:21
Duplicate of #14

**Closed by dremin** 2022-07-19 02:21 UTC
