### ISSUE TITLE
Task View Support

### ISSUE THREAD

**Issue by jribs** [dremin/RetroBar#688] opened 2023-09-13 22:57 UTC
RetroBar is great so thank you for supporting us.

I see we have multiple monitor support. However, when attempting to use multiple desktops (Win + Tab), Retrobar maintains the total number windows open throughout all desktops.

Is it feasible to:
- Have a Task View option
- Support showing windows which are only represented when switching to that desktop

Thanks again for all your hard work

**Comment by TheSystemGuy1337** [comment] 2023-10-02 16:33
Use WIN+TAB instead.

**Comment by RoPezGon561** [comment] 2024-02-14 01:31
> Use WIN+TAB instead.

This does not provide the feature to only see windows specific to separate desktops. I'd like that feature too, only thing preventing me from using RetroBar.

**Comment by dremin** [comment] 2024-12-02 01:07
Closing as duplicate of #131, which I have a fix coming for.

**Closed by dremin** 2024-12-02 01:07 UTC
