### ISSUE TITLE
multi monitor. no start menu button on other screens

### ISSUE THREAD

**Issue by appletechgeek** [dremin/RetroBar#503] opened 2023-01-09 18:58 UTC
heya good day!

 i have a small issue. i seem to have no start menu buttons on my other screens when i apply the task bar to all screens.

using the windows button will still bring up the start menu on whatever screen i'm on. but no actual button.

is there a way to get the start button on all taskbars?

**Comment by dremin** [comment] 2023-04-27 23:59
Duplicate of #158

**Closed by dremin** 2023-04-27 23:59 UTC
