### ISSUE TITLE
Language bar is missing from the tray in Windows 11

### ISSUE THREAD

**Issue by kiryanov** [dremin/RetroBar#183] opened 2021-12-05 10:37 UTC
Hi,

Whatever the settings are, Windows 11 language bar is never displayed in the tray area of RetroBar. It is displayed correctly by the original Windows 11 taskbar though.

**Comment by SuperKirbylover** [comment] 2021-12-17 18:04
for me, i don't see the language bar displayed on windows 10 either. it's a little frustrating when i switch to typing in japanese and need to tap the language icon to switch to hiragana typing...

unless this is talking about something else LMAO

**Comment by JacekLub** [comment] 2022-01-03 07:49
The keyboard lang switcher is missing also in Win10.
From the perusal of RetroBar's source code ver. 1.6. it seems that RetroBar doesn't provide any support for the kbd lang switcher docked on the taskbar and ignores it. It is a missing functionality.
As a result, when you run the RetroBar, the kbd lang switcher dissapears from the screen and becomes inaccessible.

A workaround is to reconfigure the kbd lang switcher.
Note: Win10 has two different applications which do basically the same ie. they both switch the keyboard language; one is called "Input indicator" and it can be put on and off via the Win10 taskbar settings; the second one is named "desktop language bar" ant this one only is able to work together with RetroBar (as of ver 1.6).

Configuration in Windows10:

1) Activate the "desktop language bar":
Win10 "Settings" > "Time & language" > "Keyboard", it opens the "Keyboard" window, in which pls check on the "Use the desktop language bar when it is accessible" option;

2) Undock the the "desktop language bar" from the Win10 taskbar and put it in the float-over-the-desktop mode:
In the same "Keyboard" window click the link under the words "language bar options", it open the "Text services and Input Languages" window, in which on the tab "Language Bar" pls check on the "Floating on Desktop" option;

After the above reconfiguration, when RetroBar is running, the "desktop language bar" shall be visible as a combobox floating over the desktop beyond the taskbar, this combobox contains a dropdown list of the kbd lang layouts installed in Windows.

But, the above is only a half-solution. It is necessary to add the support for Windows kbd lang switchers to RetroBar.

![01_Settings_Win10](https://user-images.githubusercontent.com/97013950/147908628-92da5afd-eaab-428f-aba2-6ab5fac45128.png)
![02_Settings-Time Language-Language](https://user-images.githubusercontent.com/97013950/147908630-45c0a150-30f9-4b95-8799-81b96514ae04.png)
![03_Keyboard](https://user-images.githubusercontent.com/97013950/147908631-200570bd-c142-435f-aaa7-3c4d8b51e8b1.png)
![04_Keyboard-Lang_bar_options](https://user-images.githubusercontent.com/97013950/147908633-dac5d6d9-6d99-4af3-848d-c925f31d3991.png)
![05_RetroBar+Kbd_lang_switch_Win10](https://user-images.githubusercontent.com/97013950/147908634-0cc47425-ecfa-49ed-8a3b-9b31e1f8058c.png)

**Comment by dremin** [comment] 2022-07-19 01:52
Duplicate of #68

**Closed by dremin** 2022-07-19 01:52 UTC
