### ISSUE TITLE
Drag/Re-Order Taskbar Programs (and customize notifications)

### ISSUE THREAD

**Issue by ckpager** [dremin/RetroBar#194] opened 2021-12-24 11:05 UTC
The Taskbar tabs representing running applications are fixed in the order they were opened.  Could they not be dragged into a different sequence?  This was possible in previous XP emulations.  Sometimes when flipping back & forth between two applications, it's very helpful to put the tabs adjacent to each other on the taskbar.

Also the lower right notification area: under previous versions, I could customize which icons are always shown, never shown, or whon only for notifications.  This was very helpful.  Now the only option is to "collapse notification area icons," and this doesn't let me specify which 3 icons are always visible, versus the remainder which are collapsed.

(Apologies if this is naïve/inappropriate: I am a newbie and incredibly grateful that this even exists.  I've just updated from Windows8.1/Classic Shell to Windows 11 with OpenShell+RetroBar emulating Windows XP)

**Comment by dremin** [comment] 2022-01-12 07:40
Thanks for the kind words, glad you are enjoying RetroBar!

For dragging taskbar items, that is fixed in the next release under #19. Customizing notification area icons is also fixed in the next release under #47.

Closing this as a duplicate of those, which I will update when the next release is published.

**Closed by dremin** 2022-01-12 07:40 UTC
