### ISSUE TITLE
please i beg of you, add a windows 7 aero theme

### ISSUE THREAD

**Issue by IncompetentMoron** [dremin/RetroBar#935] opened 2024-10-23 06:05 UTC
pretty please with a cherry on top
with all my heart i am begging you
i know you said something about retrobar emulating the pre windows 7 era or something, but hear me out

windows 7 came out in 2009, its aero theme is already pretty retro and iconic, it has been a part of many peoples childhoods including mine. who doesnt love aero? and personally, out of vista and 7, windows 7 pulls off the aero far better. also you have definetly noticed that a lot of people want to see a windows 7 theme for retrobar, so it is already pretty sought after.
in general it would be really awesome to see a 7 aero theme on retrobar

**Comment by IncompetentMoron** [comment] 2024-10-23 06:22
im sorry if im bothering you with a duplicate request, but its been nagging me for years now and i dont know whether youre considering it or if you still dont have plans on it

**Comment by 0x5066** [comment] 2024-10-23 09:36
![image](https://github.com/user-attachments/assets/4272aa51-6958-4f78-8616-e545b0200e15)
Duplicate of a lot of issues/feature requests.

**Comment by dremin** [comment] 2024-11-29 21:58
Closing as duplicate of #45.

**Closed by dremin** 2024-11-29 21:58 UTC
