### ISSUE TITLE
Add language bar

### ISSUE THREAD

**Issue by Lum1nial** [dremin/RetroBar#494] opened 2022-12-21 15:03 UTC
This would be suitable for bilingual users who use multiple keyboard layouts.

Currently, the taskbar language bar doesn't show up on RetroBar's taskbar. As a result, I have to use the desktop language bar with "Floating On Desktop" setting.
![image](https://user-images.githubusercontent.com/75108295/208935233-a761e7e6-070e-44c0-8741-e6f5d1159459.png)
![image](https://user-images.githubusercontent.com/75108295/208935532-be0d81ed-64bc-4588-8694-9b9dd41633a3.png)
![image](https://user-images.githubusercontent.com/75108295/208935787-7ca88aa4-f6c8-4bfb-89bf-aff73abb2aa4.png)
![image](https://user-images.githubusercontent.com/75108295/208935962-1d3bfc8b-d91f-4dee-a3d6-66ae8c250907.png)

**Comment by 1280px** [comment] 2023-01-08 13:31
One of the features I really want to be in RetroBar. As someone who uses 2 different languages, I find it extremely inconvenient to not have an option see what language you'll be typing in.

As a temporary workaround, you can use <s>good</s> old program called AmpMaple, which, however, is kinda nostalgic, especially if you ever used old non-English WinPEs :)

**Comment by dremin** [comment] 2023-04-27 23:58
Duplicate of #68

**Closed by dremin** 2023-04-27 23:58 UTC
