### ISSUE TITLE
[Request] Option to group taskbar buttons of the same app?

### ISSUE THREAD

**Issue by chloe-burbank** [dremin/RetroBar#274] opened 2022-03-14 03:53 UTC
like in windows xp innit
![image](https://user-images.githubusercontent.com/94586008/158102095-d7fba5a9-a2fa-4a6b-a474-039963566752.png)

**Comment by Lianaja32** [comment] 2022-03-14 09:17
I agree, that would be great in RetroBar because that's how it behaves in Windows XP.

**Comment by xoascf** [comment] 2022-03-14 23:07
Duplicate of #119

**Closed by xoascf** 2022-03-14 23:07 UTC
Labels: duplicate
