### ISSUE TITLE
Resize taskbar width for vertical bar

### ISSUE THREAD

**Issue by eltakin** [dremin/RetroBar#647] opened 2023-08-01 15:17 UTC
is it possible to add resizing taskbar width for vertical taskbar till start button width or even less.
although i'm not sure  does  win95-98-me  have this one.
![retrobarwidth](https://github.com/dremin/RetroBar/assets/26516102/f632e780-f607-4b2a-81b1-d76feaa049e7)

**Comment by 111ebobo** [comment] 2023-08-01 22:53
In windows 9x the button was centered

**Comment by eltakin** [comment] 2023-08-16 10:10
suddenly, the one of  earliest  build support one. needs the same possibility here.

https://github.com/dremin/RetroBar/assets/26516102/c91ff619-4d13-48af-8ead-5f273cb98a4a

**Comment by eltakin** [comment] 2023-08-16 10:14
suddenly, the one of earliest build support one. needs the same possibility.
[Uploading strat_menu_resizing.zip…]()

**Comment by dremin** [comment] 2023-11-12 06:04
Duplicate of #14

**Closed by dremin** 2023-11-12 06:04 UTC
