### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Cadmium620** [dremin/RetroBar#676] opened 2023-09-08 21:03 UTC
Add the Windows 7 Classic, Basic and Aero Taskbar 
![image](https://github.com/dremin/RetroBar/assets/106585614/a09b609e-6df1-4594-9c9a-1b464de4335b)

**Comment by 111ebobo** [comment] 2023-09-08 21:55
It uses a different technology so the won't be added

**Comment by dremin** [comment] 2024-11-29 21:37
Duplicate of #45

**Closed by dremin** 2024-11-29 21:37 UTC
