### ISSUE TITLE
Add Multi-Language Panel

### ISSUE THREAD

**Issue by 1280px** [dremin/RetroBar#305] opened 2022-03-29 08:33 UTC
Very important feature for people who use 2 or more languages
on their computers on a daily basis. 

An icon indicates the language that's currently in use:
![изображение](https://user-images.githubusercontent.com/71165491/160566083-db374a5e-7135-4834-a106-d550a98afd3c.png)

When clicked, it shows list of all available languages along
with language panel shortcut. Right-click shows more language
settings (most of which are either obsolete or currently
not supported by RetroBar):
![изображение](https://user-images.githubusercontent.com/71165491/160566229-d82e6b7d-e2ee-4d74-8d14-7d29a01402fb.png)

_For some languages (e.g. Japanese) it'll also require
to implement additional IME buttons, but most languages
only use the language switch button, making it more
important to being implemented first._

**Comment by dremin** [comment] 2022-07-19 02:18
Duplicate of #68

**Closed by dremin** 2022-07-19 02:18 UTC
