### ISSUE TITLE
[Suggestion] Use dark system tray icons on Windows 10

### ISSUE THREAD

**Issue by sg-epk-jtk93-x29-jp** [dremin/RetroBar#95] opened 2021-09-17 15:54 UTC
In RetroBar on Windows 10, the system tray icons always default to white even if light mode is enabled.
When the regular Windows 10 taskbar is set to light mode, the system tray icons for the network, volume, and etcetera are changed from white to black.
Opening RetroBar while in light mode, the system tray icons revert to white, which is hard to see on any theme other than Windows XP Blue.

**Comment by xoascf** [comment] 2021-09-17 16:21
Duplicate of #41

**Closed** 2021-09-24 23:38 UTC
