### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by marcopirani79** [dremin/RetroBar#698] opened 2023-10-10 09:34 UTC
Should be really usefull to anyone that are used to have a lot of application opened to implement the possibility to enlarge the bar to have multiple rows as in the image below.
Personally I will pay to to have this feature back on the Start Bar

![RQ8WzDP](https://github.com/dremin/RetroBar/assets/147495958/b03b3bcc-1b31-4c8f-8cf7-e57cc4b0c6cf)

**Comment by 2018robert** [comment] 2023-10-11 11:37
This is the same as issue  #14

**Comment by dremin** [comment] 2023-11-12 05:55
Duplicate of #14

**Closed by dremin** 2023-11-12 05:55 UTC
