### ISSUE TITLE
Buttons of multiple app instances dont combine into one

### ISSUE THREAD

**Issue by jirkacapek123** [dremin/RetroBar#356] opened 2022-06-27 22:20 UTC
Could this feature be added?
![image](https://user-images.githubusercontent.com/7817440/176045355-b9ff3411-fea6-4253-a4a2-4347a7a678a5.png)

**Comment by dremin** [comment] 2022-07-19 02:30
Duplicate of #119

**Closed by dremin** 2022-07-19 02:30 UTC
