### ISSUE TITLE
request: Windows 7 theme needed

### ISSUE THREAD

**Issue by ikkqqstudio** [dremin/RetroBar#886] opened 2024-07-14 15:03 UTC
because Windows 7 is out of support and we want to add windows 7 Taskbar @dremin

**Comment by Scratcher3** [comment] 2024-07-14 17:17
then get a theme tool ;-;

**Comment by ikkqqstudio** [comment] 2024-07-15 08:22
> then get a theme tool ;-;

what is that

**Comment by ikkqqstudio** [comment] 2024-07-16 11:45
> then get a theme tool ;-;

I mean add Windows 7 Taskbar to Retrobar not theme

**Comment by ikkqqstudio** [comment] 2024-07-16 11:50
#85 #884 #785 #577

**Comment by dremin** [comment] 2024-07-17 00:54
Duplicate of #45

**Closed** 2024-07-17 00:54 UTC

**Comment by ikkqqstudio** [comment] 2024-07-17 11:44
fine

**Comment by WindClan** [comment] 2024-07-20 22:39
#832 #785 #45 #771 #592 #584 #582 #581 #579 #577 #565 #507 #491 #490 #488 #485 #478 #465 #451 #215 #168 #80 #884

**Comment by AngrySonics** [comment] 2024-07-21 23:48
it might be possible to make a custom Windows 7 theme. i haven't experimented with custom themes yet so i dunno for sure
