### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by wilson821** [dremin/RetroBar#321] opened 2022-04-09 08:23 UTC
add windows vista taskbar(the black one) at the next update

**Comment by 1280px** [comment] 2022-04-10 16:15
Duplicate of #15, please close the issue.

p.s. You may be interested in this PR: https://github.com/dremin/RetroBar/pull/287

**Comment by dremin** [comment] 2022-07-13 04:03
Closing as duplicate of #15 (which the PR is linked to).

**Closed by dremin** 2022-07-13 04:03 UTC
