### ISSUE TITLE
[Request] Deskband toolbar Extension support

### ISSUE THREAD

**Issue by JeremyLyokoPPG2020** [dremin/RetroBar#125] opened 2021-10-19 12:34 UTC
toolbar Extension on Retrobar
![image](https://user-images.githubusercontent.com/30205044/137910424-1593b665-0370-4a3d-a012-b0b099028f55.png)

**Comment by dremin** [comment] 2022-07-19 01:52
Duplicate of #42

**Closed by dremin** 2022-07-19 01:52 UTC
