### ISSUE TITLE
Windows 7 theme?

### ISSUE THREAD

**Issue by home-gihub** [dremin/RetroBar#577] opened 2023-05-13 07:40 UTC
so I have been looking for a taskbar replacement that also replaces the buttons and RetroBar has been the closest I've got to that but I looked in the themes then saw that there was no windows 7 theme, i looked for a community-made win 7 theme, but no luck.
I know that windows 7 is sort of modern but i really like the windows 7 style. there is a vista theme but i want a windows 7 theme.

**Comment by SwiftyPeed** [comment] 2023-05-13 14:58
I have also really wanted a windows 7 theme and I think it would be a great alternative to window blinds and classic shell for the taskbar. and it would be even better since that retrobar has the ability to change the flyout menus.

**Comment by home-gihub** [comment] 2023-05-13 15:48
i did see some classuc shell taskbar theme but that only has start buttons and texture

**Comment by 111ebobo** [comment] 2023-05-13 22:47
First of all, you can use startisback, and second of all vista theme is better

**Comment by home-gihub** [comment] 2023-05-14 08:01
but stardock costs money

**Comment by SwiftyPeed** [comment] 2023-05-14 14:11
Retro bar is free and has functional flyouts. And combine that with open shell for the start menu. You've got a free Windows 7 Taskbar and menu.

**Comment by home-gihub** [comment] 2023-05-14 14:13
but retrobar don't have windows 7 skin

**Comment by 111ebobo** [comment] 2023-05-14 14:33
Use startisback

**Comment by home-gihub** [comment] 2023-05-14 14:34
didn't i tell you? stardock costs money

**Comment by TheDolphinSlayer** [comment] 2023-05-15 03:47
I don't know why everybody is so against the Windows 7 taskbar theme, Windows 7 literally came out in 2009, two years apart from vista, it is 2023, how is it not considered retro enough to have a theme? Is it too difficult to code? I mean I understand since Windows 7 had mouseovermask that chose color based on the primary color of an Icon, and the systemtray had a flyout, but still think that could be useful as it could have a "Customize" button that can be used to open the systray customizer IN retrobar

There's already working aeroblur, and ways to fix the start button that have been implimented in recent builds, I just don't really see why it can't be made. Obviously we know that the superbar was different, but windows 7 still gave the option to NOT combine taskbar items and decrease the taskbar size

+ They introduced a show Desktop Button which was a feature literally none of those os's had BUT windows 7 and on

**Comment by 111ebobo** [comment] 2023-05-15 06:10
yes windows 7 is not a retro os, and its not suitable in retrobar because its too big

**Comment by 111ebobo** [comment] 2023-05-15 06:11
> didn't i tell you? stardock costs money i don't want my taskbar begging for money

wait. but its free, i have always used it and its didn`t asked me to pay

**Comment by home-gihub** [comment] 2023-05-15 14:54
> > didn't i tell you? stardock costs money i don't want my taskbar begging for money
> 
> wait. but its free, i have always used it and its didn`t asked me to pay
https://www.stardock.com/products/windowblinds/download
have you looked?

**Comment by 111ebobo** [comment] 2023-05-15 16:41
> > > didn't i tell you? stardock costs money i don't want my taskbar begging for money
> > 
> > wait. but its free, i have always used it and its didn`t asked me to pay
> 
> https://www.stardock.com/products/windowblinds/download
> have you looked?
> 

This is windowsblinds

**Comment by home-gihub** [comment] 2023-05-16 14:51
> 

then send me this "free" stardock software

**Comment by 111ebobo** [comment] 2023-05-17 06:28
> 

here https://filecr.com/windows/startisback/?id=363752270000

**Comment by xoascf** [comment] 2023-05-17 06:54
Please don't add download links to cracked software next time, thanks!
Duplicate of #45.

**Closed by xoascf** 2023-05-17 06:54 UTC
