### ISSUE TITLE
win + 1

### ISSUE THREAD

**Issue by zovcoder** [dremin/RetroBar#787] opened 2024-04-05 14:31 UTC
hello, very used to the key combinations win + 1, win + 2, etc. It is very convenient to change through windows and programs. But retrobar does not have such a combination. I think it would be very pleasant for some users like me.

**Comment by 111ebobo** [comment] 2024-04-05 21:04
It doesn't work because this taskbar icons are just shortcuts like that one on your desktop (same was even in older windows versions)

**Comment by zovcoder** [comment] 2024-04-05 21:07
> It doesn't work because this taskbar icons are just shortcuts like that one on your desktop (same was even in older windows versions)

But on the same windows vista there was this keyboard shortcut. So I think it makes sense to add this. because of this problem, I can't use it at all

**Comment by 111ebobo** [comment] 2024-04-07 21:05
> > It doesn't work because this taskbar icons are just shortcuts like that one on your desktop (same was even in older windows versions)
> 
> But on the same windows vista there was this keyboard shortcut. So I think it makes sense to add this. because of this problem, I can't use it at all

Actually I didn't know that fact about Vista, but still this quick launch is just a bunch of shortcuts so they're not working with that key binds

**Comment by zovcoder** [comment] 2024-04-07 21:11
> > > It doesn't work because this taskbar icons are just shortcuts like that one on your desktop (same was even in older windows versions)
> > 
> > 
> > But on the same windows vista there was this keyboard shortcut. So I think it makes sense to add this. because of this problem, I can't use it at all
> 
> Actually I didn't know that fact about Vista, but still this quick launch is just a bunch of shortcuts so they're not working with that key binds

without you i know it

**Comment by Nxkorasu** [comment] 2024-04-08 08:34
> It doesn't work because this taskbar icons are just shortcuts like that one on your desktop (same was even in older windows versions)

Knowing this you could add a shortcut specific "key combination" or keyboard shortcut (tho you are forced to Ctrl + Alt + (custom))

**Comment by dremin** [comment] 2024-11-29 22:26
Closing as duplicate of #70.

**Closed by dremin** 2024-11-29 22:26 UTC

**Comment by xoascf** [comment] 2025-05-07 00:39
You can now use the win + number key combinations since they are now available in the latest version - you can use them to quickly switch through open applications or open Quick Launch items, you'll need to change the default behavior in **RetroBar Properties** > **Advanced** tab as this is disabled by default.
