### ISSUE TITLE
Please add the windows vista   theme please 

### ISSUE THREAD

**Issue by xTmmm** [dremin/RetroBar#275] opened 2022-03-14 14:01 UTC
please
![image](https://user-images.githubusercontent.com/86075685/158187932-789635b5-ba7c-498d-aa71-a2222a519912.png)

**Comment by ColdSalt09** [comment] 2022-03-14 16:59
![εικόνα](https://user-images.githubusercontent.com/77743845/158222526-4edd0571-58f2-4f07-bda4-4654c2116cf7.png)
Im trying but i cant its so hard

**Comment by xoascf** [comment] 2022-03-14 20:27
I can work on this, it looks easy enough to do!

**Comment by xoascf** [comment] 2022-03-14 20:28
Oops...
Duplicate of #15

**Comment by xTmmm** [comment] 2022-03-14 20:46
why

**Comment by xoascf** [comment] 2022-03-14 20:57
Duplicate of #15

**Closed by xoascf** 2022-03-14 20:57 UTC
Labels: duplicate

**Comment by markyb86** [comment] 2022-03-19 16:47
I've gotten pretty close , although the start orb does not overlap
![image](https://user-images.githubusercontent.com/34405495/159130363-3138a740-1e9e-4309-aabc-f60090058c3f.png)

**Comment by XTMYTYT** [comment] 2022-03-19 16:57
NICE!

**Comment by XTMYTYT** [comment] 2022-03-19 16:58
can u send me theme

**Comment by markyb86** [comment] 2022-03-20 12:07
https://github.com/markyb86/RetroBar

you need 
retrobar\controls\Vista Frame.xaml
retrobar\resources\startvista.png
retrobar\resources\startvistablue.png
retrobar\themes\Vista Ultimate.xaml

I believe it will not work unless you have retrobar 1.7, with all of the supporting files extracted

![image](https://user-images.githubusercontent.com/34405495/159161405-da5cfbd4-3b97-48ef-a6e2-28dbc5399f3e.png)
