### ISSUE TITLE
Some odd error when opening CMD

### ISSUE THREAD

**Issue by metrochel** [dremin/RetroBar#778] opened 2024-03-15 20:18 UTC
Any time I open up a cmd window, this error pops up, forcing me to restart RetroBar. 
![image](https://github.com/dremin/RetroBar/assets/158221670/22b60a48-6830-4165-ad95-6fa1fcd27dd3)
Also, clicking "Yes" does not restart RetroBar, it just crashes.
Any idea what may be causing this?

**Comment by dremin** [comment] 2024-03-16 00:18
This happens with the "Show input language" option enabled. It's a known issue and will be fixed with the next release!

**Comment by dremin** [comment] 2024-04-21 21:47
Duplicate of #758 which will be fixed in the next release.

**Closed by dremin** 2024-04-21 21:47 UTC
