### ISSUE TITLE
Add quick back to desktop on setting

### ISSUE THREAD

**Issue by BHD1673** [dremin/RetroBar#495] opened 2022-12-22 13:42 UTC
pls adding it

**Comment by 1280px** [comment] 2023-01-01 14:34
There's already a [pull request](https://github.com/dremin/RetroBar/pull/169) to implement "Show Desktop" button, but for some reason it's been in drafted state for over a year now. However, you can compile it yourself, or fork [xoascf's fork](https://github.com/xoascf/RetroBar/tree/show-desktop-button) and download autocompiled version from thw "Actions" tab.

**Comment by dremin** [comment] 2023-04-27 02:03
Duplicate of #84

**Closed by dremin** 2023-04-27 02:03 UTC
