### ISSUE TITLE
Start Menu doesn't open

### ISSUE THREAD

**Issue by Xelemental69** [dremin/RetroBar#273] opened 2022-03-13 14:05 UTC
I have W11 in my system and suddenly while I tried to open the Start Menu in RetroBar, it didn't open, both OpenShell and the default W11 start menu. I also tried previous versions of RetroBar and the error still happened. It is something with an W11 update or is it may have something to do with the configuration?

**Comment by xoascf** [comment] 2022-03-13 18:03
I confirm that this is the case. Are you using a Windows 11 Insider Preview build?

**Comment by dremin** [comment] 2022-03-13 18:15
The start menu is working for me on insider build 22572.

**Comment by xoascf** [comment] 2022-03-13 18:19
In my case, it does not usually open in that compilation, but if I press the button on the keyboard it does work.

**Comment by Xelemental69** [comment] 2022-03-13 18:21
I'n not using any insider preview builds.
And also, it doesn't open with the Windows menu when RetroBar is active

**Comment by xoascf** [comment] 2022-03-14 21:53
Here is an example:

https://user-images.githubusercontent.com/28744392/158266875-083f673b-61c9-4ae5-9af9-571cd0b5b0d6.mp4

First attempt: The Start menu opens when any normal window is active.
Second attempt: The Start menu does not open when an application like Spy++ is active.
Third attempt: The Start menu opens when an application like Spy++ is active, but by pressing the Windows key instead of the Start button.

**Comment by dremin** [comment] 2022-03-14 22:25
@xoascf I made a ManagedShell branch `traymonitor-harder` which I think _might_ help this. If you build RetroBar using ManagedShell from that branch, does it work better?

**Comment by xoascf** [comment] 2022-03-14 23:36
> @xoascf I made a ManagedShell branch `traymonitor-harder` which I think _might_ help this. If you build RetroBar using ManagedShell from that branch, does it work better?

Yes, but now I was trying to implement the Start button orb as a popup or secondary floating window, but it was still not working in my custom build when I was using Spy++.

**Comment by xoascf** [comment] 2022-03-14 23:43
I think it would be better to make the Start button a separate window.

**Comment by dremin** [comment] 2022-03-21 06:33
Is this maybe a duplicate of #112?

**Comment by dremin** [comment] 2022-07-19 01:59
Duplicate of #112.

**Closed by dremin** 2022-07-19 01:59 UTC
