### ISSUE TITLE
[Request] Show Taskbar when non-fullscreen app/program is focused

### ISSUE THREAD

**Issue by SupahMario** [dremin/RetroBar#227] opened 2022-01-18 01:15 UTC
So, opening a window that ends up taking the full screen space of the current monitor hides the taskbar. The idea is that if you alt-tab to another program or a program forces focus onto itself that is a normal window, the taskbar would reveal itself as to allow access to other programs and the notification area. When the full-screen program regains focus, the taskbar would hide itself again.
This is how the normal taskbar behaves with applications or programs that fill up the entire screen space. Would definitely help with accessing programs that reside within the notification area while a full-screen app/program is open.

**Comment by dremin** [comment] 2022-04-12 04:12
Closing as duplicate of #171.

**Closed by dremin** 2022-04-12 04:12 UTC
