### ISSUE TITLE
RetroBar crash on opening PowerShell

### ISSUE THREAD

**Issue by FrostedGeulleisia** [dremin/RetroBar#770] opened 2024-03-09 20:00 UTC
![RetroBar_Sbe7HdBu98](https://github.com/dremin/RetroBar/assets/27410260/02074a6f-0d8b-4f47-a4c5-0f2a54a74993)
Happens consistently on opening PowerShell via Shift+RightClick in directory > "Open PowerShell window here"
using latest x64 on Win10 (build 19045.3448)

**Comment by dremin** [comment] 2024-04-21 21:46
Duplicate of #758 which will be fixed in the next release.

**Closed by dremin** 2024-04-21 21:46 UTC
