### ISSUE TITLE
Restarting Explorer causes windows to no longer respect the taskbar area and overlap it

### ISSUE THREAD

**Issue by TorutheRedFox** [dremin/RetroBar#714] opened 2023-11-18 15:15 UTC
If Explorer is restarted, windows and the desktop act as if there's no taskbar anymore until you relaunch RetroBar too.

**Comment by elaymm5** [comment] 2023-11-26 12:47
> If Explorer is restarted, windows and the desktop act as if there's no taskbar anymore until you relaunch RetroBar too.

This happens because retrobar enables "hide automatically hide taskbar in desktop mode"

**Comment by 1JustJoey** [comment] 2024-01-06 17:55
Just go to settings and unhide the  taskbar if you aren't using a transparent theme.

**Comment by dremin** [comment] 2024-11-21 06:58
This is fixed by #945.

**Comment by dremin** [comment] 2024-11-29 21:18
Just realized this is a duplicate of #96, moving the tracking to that bug.

**Closed by dremin** 2024-11-29 21:18 UTC
