### ISSUE TITLE
[Request] Windows Vista/7 taskbar pls 🥺👉👈?

### ISSUE THREAD

**Issue by gayfieri** [dremin/RetroBar#168] opened 2021-11-18 03:47 UTC
i am on windows 11 and i'm not really vibing with how the taskbar looks normally so i use taskbar so i was wondering if there could be a chance of them to be added

**Comment by Andrej123456789** [comment] 2021-11-19 09:44
Good idea, but they postpone because Win7 taskbar work on all monitors and they want loose time

**Comment by BrightsydeJacobDev** [comment] 2021-12-10 13:03
@Andrej123456789 for the Win7 Taskbar, the closest one is to use StartIsBack++ (for 8.1 and 10) or StartAllBack on Windows 11, but the ORB is slightly less accurate than Windows 7 version due to the smooth borders outside missing.

**Comment by dremin** [comment] 2021-12-20 04:17
Duplicate of #15 (Vista) / #45 (7)

**Closed by dremin** 2021-12-20 04:17 UTC

**Comment by ColdSalt09** [comment] 2022-02-28 17:52
@dremin  here's a longhorn theme I made using @Ipmusicon's royale noir theme
![εικόνα](https://user-images.githubusercontent.com/77743845/156033184-e873d450-61c0-44de-bf90-f6eb1b83a1de.png)
