### ISSUE TITLE
Windows Vista Theme

### ISSUE THREAD

**Issue by Roszek-Dragon** [dremin/RetroBar#63] opened 2021-08-29 13:24 UTC
Despite what people think about WinVista, it had the most dazzling looks ever.
Please, add a Vista taskbar theme for this amazing program. It would fit much better with my Windows 11 Dark Mode.

**Comment by Andrej123456789** [comment] 2021-08-30 07:16
And Windows 7

**Comment by JuanjoSevilla1** [comment] 2021-08-31 08:58
I love Windows 7 👍

**Comment by 1280px** [comment] 2021-09-09 13:31
Yes please!!! It'd be amazing to have it

Also because it mostly functionally similar to Windows XP's one, in theory, it shouldn't take much time to implement it (this is just my assumptions though) without window thumbnails

**Comment by ComputeriFan431** [comment] 2021-09-13 11:24
and the Windows Longhorn Build 5112 theme for the windows taskbar.

**Comment by dremin** [comment] 2021-09-24 23:34
Duplicate of #15

**Closed by dremin** 2021-09-24 23:34 UTC
