### ISSUE TITLE
windows 11 taskbar and retrobar are having a problem after i just updated windows 11 from windows updates.

### ISSUE THREAD

**Issue by Mustardnote3943** [dremin/RetroBar#260] opened 2022-02-24 02:41 UTC
I was watching youtube on opera GX and then the update was ready then I restart then retrobar is having difficulty with Windows 11 taskbar. I'm stuck on windows 11 btw (go back option is no longer available). let me explain what's wrong, the windows 11 taskbar reappears behind retrobar then they both I think or only retrobar doesn't respond anymore then the windows 11 taskbar disappears then everything is back to normal. this seems to be happening when my laptop is on screensaver after being idle then stop the screensaver or wake it. (if you're wondering what I mean by update, it's just windows update.) retrobar has been working well on windows 11 until this update got installed. please fix this bug or maybe I just need to restart again then it might still work.

**Comment by dremin** [comment] 2022-02-24 02:44
I believe I've seen something like this before, if you log out and back in everything should be back to normal.

**Comment by Mustardnote3943** [comment] 2022-02-25 01:42
> I believe I've seen something like this before, if you log out and back in everything should be back to normal.

ok

**Comment by Mustardnote3943** [comment] 2022-02-25 02:52
> I believe I've seen something like this before, if you log out and back in everything should be back to normal.

wait dude I just exit retrobar and then windows 11 taskbar is no longer responding (I did a tweak on the taskbar to make it small. also, I only have the windows 11 taskbar on external monitor. the problem is still happening. its the same issue again. its not resolved.

**Comment by dremin** [comment] 2022-03-13 20:03
> I did a tweak on the taskbar to make it small

Out of curiosity, does it behave normally without the tweak installed?

**Comment by Mustardnote3943** [comment] 2022-03-14 18:28
> > I did a tweak on the taskbar to make it small
> 
> Out of curiosity, does it behave normally without the tweak installed?

not sure, but by adding the classic windows 10 taskbar tweak. it fixes it but it disables clipboard, screenshot and other things such as xbox game bar. they require windows 11 taskbar for these to enable. windows 11 is shitty. im stuck on it.

**Comment by dremin** [comment] 2022-03-21 06:34
I believe this is a duplicate of #112.

**Closed by dremin** 2022-03-21 06:34 UTC
