### ISSUE TITLE
Window still shows despite closing it

### ISSUE THREAD

**Issue by SuperKirbylover** [dremin/RetroBar#317] opened 2022-04-08 02:26 UTC
sometimes, after playing a source engine game on steam in fullscreen, when i exit, it doesn't really go away on the taskbar. even closing another window doesn't make it disappear
opening enough windows to "replace" it (opening windows until a window replaces the closed out application's window tab) is the only way to fix it
![image](https://user-images.githubusercontent.com/37816816/162350903-cac6de2c-8105-44ba-b0af-c6e2895bb383.png)

here's my build if important
![image](https://user-images.githubusercontent.com/37816816/162351149-5574bcb9-9e55-4998-9f7b-a1276fd2029c.png)

**Comment by xoascf** [comment] 2022-04-08 05:26
Duplicate of #86

**Comment by dremin** [comment] 2022-04-08 05:45
When you right-click it do you get a menu with close/minimize/etc, or do you get a menu with task manager, properties, and exit?

**Comment by SuperKirbylover** [comment] 2022-04-08 17:52
> When you right-click it do you get a menu with close/minimize/etc, or do you get a menu with task manager, properties, and exit?
the latter; i only get the task manager / properties / exit menu

**Comment by dremin** [comment] 2022-04-08 18:06
Interesting, I think this may actually be a graphics/rendering issue. In RetroBar settings, if you enable software rendering, then open and close the game, does the issue persist?

**Comment by SuperKirbylover** [comment] 2022-05-26 21:01
sorry it took so long to respond! things got super busy.
i enabled software rendering and it didn't seem to happen!

**Comment by dremin** [comment] 2022-05-26 23:33
No worries, thanks for checking! This unfortunately points to something out of our hands, most likely a graphics driver issue. If you'd like to try hardware rendering again in the future, I'd recommend updating the driver if possible to see if it helps.

**Closed by dremin** 2022-05-26 23:33 UTC
Labels: duplicate
