### ISSUE TITLE
I want to hide RetroBar System Tray icons.

### ISSUE THREAD

**Issue by TK50P** [dremin/RetroBar#540] opened 2023-03-10 11:08 UTC
is there to hide system tray icon? (e.g network, sound)
Because I transformed 10 to XP. and I added windows xp style volume and network icon. but Windows 10 network and volume icons not hided.
![hide](https://user-images.githubusercontent.com/127497974/224300513-7ce5272a-a7bc-42de-8fb6-278153d5dafe.png)

**Comment by TK50P** [comment] 2023-03-10 23:19
Not working, I turned off all visible icons in taskbar (not retrobar) 
![hide](https://user-images.githubusercontent.com/127497974/224446003-e5d623cb-214c-4eb9-8f7c-f63824fd41f0.png)

**Comment by 111ebobo** [comment] 2023-03-10 23:31
> Not working, I turned off all visible icons in taskbar (not retrobar) 
> ![hide](https://user-images.githubusercontent.com/127497974/224446003-e5d623cb-214c-4eb9-8f7c-f63824fd41f0.png)
> 

I meant in retrobar

**Comment by TK50P** [comment] 2023-03-10 23:49
Thank you! I fixed to enable like this
![hide](https://user-images.githubusercontent.com/127497974/224449573-8c72021c-44dc-439e-83fd-859b406784c2.png)
![11](https://user-images.githubusercontent.com/127497974/224449585-24a7265b-a35c-4203-8cd0-e5ec79cfd95d.PNG)

**Comment by 111ebobo** [comment] 2023-03-11 23:03
> Thank you! I fixed to enable like this
> ![hide](https://user-images.githubusercontent.com/127497974/224449573-8c72021c-44dc-439e-83fd-859b406784c2.png)
> ![11](https://user-images.githubusercontent.com/127497974/224449585-24a7265b-a35c-4203-8cd0-e5ec79cfd95d.PNG)
> 

Your welcome, I meant that you should do that

**Comment by dremin** [comment] 2024-04-28 08:18
Closing as a duplicate of #338 which I am working on.

**Closed by dremin** 2024-04-28 08:18 UTC
