### ISSUE TITLE
Feature Request: Multiple Desktop Support

### ISSUE THREAD

**Issue by RoPezGon561** [dremin/RetroBar#779] opened 2024-03-21 03:14 UTC
When switching between desktops, I would only like to see tabs for programs open within that desktop. Right now, I see all the tabs for all the programs on all the desktops. I would rather see the programs open on the current desktop.

**Comment by LilacMonarch** [comment] 2024-04-05 04:34
![image](https://github.com/dremin/RetroBar/assets/26831349/cdfa8fa6-626a-4f74-ba70-21aab98182f4)
Do you have it set to "same taskbar as window"?

**Comment by fan-young** [comment] 2024-10-26 22:43
> ![image](https://private-user-images.githubusercontent.com/26831349/319858890-cdfa8fa6-626a-4f74-ba70-21aab98182f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5ODI2NDMsIm5iZiI6MTcyOTk4MjM0MywicGF0aCI6Ii8yNjgzMTM0OS8zMTk4NTg4OTAtY2RmYThmYTYtNjI2YS00Zjc0LWJhNzAtMjFhYWI5ODE4MmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDIyMzkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YzQ1NWExYjAzODlkM2M3ZjE2MDMyYjI5MTk5ODc0NDNjZjJiNTUzZmZkMjVlMWI4NDkzMmNiZjdhYTZjMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BhSD047uuL9m2smFUivIBK8qmwEdMB_XztA4oAXk1oU) Do you have it set to "same taskbar as window"?

This doesn't solve the issue

**Comment by dremin** [comment] 2024-12-02 01:07
Closing as duplicate of #131, which I have a fix coming for.

**Closed by dremin** 2024-12-02 01:06 UTC
