### ISSUE TITLE
Start menu floats above taskbar

### ISSUE THREAD

**Issue by 1xxxxxxxxx** [dremin/RetroBar#237] opened 2022-02-06 10:50 UTC
Windows 10's start menu floats above the RetroBar taskbar

**Comment by Jonson26** [comment] 2022-02-07 13:08
You need to check the "use small taskbar buttons" option in win10's taskbar settings.

**Comment by 1xxxxxxxxx** [comment] 2022-02-10 01:15
so what if it's windows 11?
Minh

**Comment by Jonson26** [comment] 2022-02-10 14:16
IIRC Windows 11 also has some sort of compact taskbar setting. It won't be pixel-perfect, but it should make it at least a little bit better.

**Comment by Jonson26** [comment] 2022-02-10 14:17
A quick google search reveals this: https://allthings.how/how-to-enable-small-taskbar-in-windows-11/

**Comment by dremin** [comment] 2022-07-19 02:12
Duplicate of #193

**Closed by dremin** 2022-07-19 02:12 UTC
