### ISSUE TITLE
Hot key Win+1/2/3 does nothing

### ISSUE THREAD

**Issue by ssssssbbb** [dremin/RetroBar#651] opened 2023-08-05 14:02 UTC
As the title mentioned, can't switch between applications by hotkey.

BTW, would you please add the funtion of changing fonts ?

**Comment by 111ebobo** [comment] 2023-08-05 22:43
Because they are just shortcuts in the folder so they can't be opened by shortcut, regular windows taskbar (starting from Windows 7 maybe) work a bit differently

**Comment by dremin** [comment] 2023-11-12 06:03
Duplicate of #70

**Closed by dremin** 2023-11-12 06:03 UTC

**Comment by xoascf** [comment] 2025-05-07 00:38
The latest update includes this feature. By default it is disabled, so you need to change the default behavior in **RetroBar Properties** > **Advanced** tab, then you can use Win+number hotkeys.
