### ISSUE TITLE
REQ - Auto-hide taskbar

### ISSUE THREAD

**Issue by RDTG** [dremin/RetroBar#469] opened 2022-11-20 09:43 UTC
This is an essential feature for anyone using an OLED monitor.

**Comment by yereverluvinunclebert** [comment] 2023-01-27 11:49
An essential function, the only 'real' functionality that retrobar lacks.

**Comment by dremin** [comment] 2023-04-27 23:43
Duplicate of #77

**Closed by dremin** 2023-04-27 23:43 UTC
