### ISSUE TITLE
autohide is needed pls add this feature

### ISSUE THREAD

**Issue by maxox** [dremin/RetroBar#544] opened 2023-03-15 18:49 UTC
autohide is needed pls add this feature

**Comment by yereverluvinunclebert** [comment] 2023-03-16 10:31
as per #469 #346 #77 #319

Always a good idea to check to see if any current issues match before opening a duplicate.

**Comment by dremin** [comment] 2023-04-27 23:43
Duplicate of #77

**Closed by dremin** 2023-04-27 23:43 UTC
