### ISSUE TITLE
Add Hide taskbar and calendar

### ISSUE THREAD

**Issue by makran7** [dremin/RetroBar#346] opened 2022-05-29 03:02 UTC
I just downloaded this and immedietly noticed the lack of a hide taskbar option so that the taskbar can drop down and that when i click on the time it doesent show the calendar like on the default windows 10 taskbar, i think these would be great additions to the app. Other than that its absolutely amazing

**Comment by dremin** [comment] 2022-07-19 02:32
Duplicate of #77 and #342.

**Closed by dremin** 2022-07-19 02:32 UTC
