### ISSUE TITLE
Blank space above the taskbar

### ISSUE THREAD

**Issue by Jonny-T-cyber** [dremin/RetroBar#453] opened 2022-10-26 09:51 UTC
Hi,
I use Windows 11 (updated) and, as the title suggests, maximizing the windows presents the problem that you can see in the attached screenshot:

![Screenshot](https://user-images.githubusercontent.com/33354144/197994375-5e435071-d8ba-4e86-b902-86cc3f89648c.jpg)

Is there any way to solve this annoying problem?
Thanks

**Comment by ozomax1997** [comment] 2022-11-14 10:45
If you have translucent TB or similar software installed disable it from opening on start-up. That should fix this issue.

**Comment by yoshiask** [comment] 2022-12-19 17:32
I don't have anything else installed and I have this issue.
```
Edition: Windows 11 Education Insider Preview
Version: 22H2
OS build: 25262.1000
Scaling: 100%
```

**Comment by dremin** [comment] 2022-12-19 20:43
I have also encountered this issue. The best solution I have found is to close RetroBar, then disable the option in Windows Settings to show the Windows taskbar on all monitors. After that, everything should be OK (RetroBar will still work on all monitors since it is a separate setting).

**Comment by yoshiask** [comment] 2022-12-19 21:42
I only have one monitor and that option is off and greyed out. However, I found that setting the taskbar to auto-hide in Settings does resolve the issue.

**Comment by dremin** [comment] 2024-11-29 22:19
Closing as the issue is resolved by the above comment.

**Closed by dremin** 2024-11-29 22:19 UTC
