### ISSUE TITLE
[ FEATURE REQUEST ] Windows 7 taskbar theme request

### ISSUE THREAD

**Issue by ghost** [dremin/RetroBar#893] opened 2024-08-05 14:29 UTC
I need Windows 7 taskbar due to Windows transformation. Please? 👉👈

**Comment by WindClan** [comment] 2024-08-09 18:41
#832 #785 #45 #771 #592 #584 #582 #581 #579 #577 #565 #507 #491 #490 #488 #485 #478 #465 #451 #215 #168 #80 #884 #886

it wont happen

**Comment by home-gihub** [comment] 2024-09-21 12:42
why?
Win 7 is EOL.

**Comment by WindClan** [comment] 2024-09-21 21:56
and it has the same taskbar as 7 and 10

and you can straight up get the Windows 7 explorer to run on 10 with taskbar and start menu
https://winclassic.net/thread/2588/explorer7-windows-explorer-10-11

**Comment by home-gihub** [comment] 2024-10-15 15:13
well, thx ig :s

**Comment by dremin** [comment] 2024-11-29 21:58
Closing as duplicate of #45.

**Closed by dremin** 2024-11-29 21:58 UTC
