### ISSUE TITLE
Wishes: drag drop of taskbar buttons(?), double height taskbar, "Show the desktop" in context menu, option to make mouse wheel click on taskbar button(?) to close the app. Else perfect!!!

### ISSUE THREAD

**Issue by osexpert** [dremin/RetroBar#165] opened 2021-11-15 00:37 UTC
Wishes: 
-drag drop of taskbar buttons(?)
Very nice to have. Drag drop of notification icons could be nice too, but not important.

-double height taskbar
A blocker for me. I always use double height taskbar.

-"Show the desktop" in context menu
Currently only show "Task Manager". Would like to see "Show the desktop" too.

-option to make mouse wheel click on taskbar button(?) to close the app
I use 7+ Taskbar Tweaker to set this normally, but RetroBar should have its own option for this.

But very promising!!! I feel this could become something huge.

**Comment by gdalsnes** [comment] 2021-11-15 00:43
And maybe option for showing a "desktop" button at the very left (show desktop button).

**Comment by 1280px** [comment] 2021-11-15 10:23
№1 is a duplicate of #19, and №2 is a duplicate of #14.

Also №5 is a possible duplicate of #84, though by default this button is located at the very right

**Comment by gdalsnes** [comment] 2021-11-15 10:31
Thanks. Yes, I ment very right, sorry. I update the comment.

**Comment by gdalsnes** [comment] 2021-11-15 10:37
I can make new items for no3 and no4 and resolve this as duplicate if you like.

**Comment by dremin** [comment] 2023-05-07 23:11
The only non-duplicate item here was middle-click to close, which is now available in the latest release!

**Closed by dremin** 2023-05-07 23:11 UTC
