### ISSUE TITLE
Dual monitor setup

### ISSUE THREAD

**Issue by Andrej123456789** [dremin/RetroBar#59] opened 2021-08-29 09:10 UTC
RetroBar doesn't show on second monitor when projecting settings is on Extended

Windows 10

**Comment by justandras** [comment] 2021-08-29 11:20
Also, you can't change which screen you want the taks bar to be on. I like to have it on ma most left monitor, while my main display is my middle screen, and I can't change the location of RetroBar.

**Comment by SIX10** [comment] 2021-09-03 20:20
> Also, you can't change which screen you want the taks bar to be on. I like to have it on ma most left monitor, while my main display is my middle screen, and I can't change the location of RetroBar.

If anything should be implemented, it should be this. Dremin has expressed resistance to adding a dual-monitor taskbar feature to Retrobar in #13 , but vanilla Windows XP DOES allow you to change the location of the taskbar in the monitor settings.

**Comment by dremin** [comment] 2021-09-24 23:35
Duplicate of #13

**Closed by dremin** 2021-09-24 23:35 UTC
