### ISSUE TITLE
[Feature Request] WinKey + Num Shortcut

### ISSUE THREAD

**Issue by Avid29** [dremin/RetroBar#929] opened 2024-10-17 07:29 UTC
Just like the built-in taskbar. WinKey + N (number), opens the Nth item on the tasklist.

**Comment by dremin** [comment] 2024-11-29 22:26
Closing as duplicate of #70.

**Closed by dremin** 2024-11-29 22:26 UTC

**Comment by xoascf** [comment] 2025-05-07 00:38
RetroBar now offers this configurable feature in its latest release.
