### ISSUE TITLE
[Request] Olive Green theme for RetroBar

### ISSUE THREAD

**Issue by ParkerGit2328** [dremin/RetroBar#202] opened 2021-12-30 04:36 UTC
Can you add the Olive Green XP theme to RetroBar please?

**Comment by scoobytheboi** [comment] 2021-12-30 16:11
https://github.com/dremin/RetroBar/issues/195

**Comment by dremin** [comment] 2022-03-10 05:17
Closing as duplicate of #195

**Closed by dremin** 2022-03-10 05:17 UTC
