### ISSUE TITLE
Feature request: Completely/always hide tray icons.

### ISSUE THREAD

**Issue by 0penrc** [dremin/RetroBar#773] opened 2024-03-12 17:27 UTC
The title.

I have an alternative for the default Windows Volume tray that looks more like XP. I want to hide it but I can't seem to do so.

Thanks.

**Comment by dremin** [comment] 2024-04-28 08:19
Closing as a duplicate of #338 which I am working on.

**Closed by dremin** 2024-04-28 08:19 UTC
