### ISSUE TITLE
[Request] Windows Vista and 7 Taskbars

### ISSUE THREAD

**Issue by WindowsNinetyTen** [dremin/RetroBar#215] opened 2022-01-14 18:59 UTC
How about adding Windows Vista and 7 to the options?

**Comment by TheDolphinSlayer** [comment] 2022-01-16 08:54
I understand the aero themes not being added but what about the basic themes? The ones that don't use transparency, the only complication i can see is the Aero Glow (which is when hovering over the taskbar task button, the cursor will glow the color of the icon)

**Comment by Void48** [comment] 2022-02-04 04:25
+1 for Vista taskbar

**Comment by gayfieri** [comment] 2022-02-15 23:50
+1 for 7 taskbar

**Comment by KibSquib48** [comment] 2022-02-25 16:29
+1 for both

**Comment by Pixel556** [comment] 2022-03-08 07:24
true

**Comment by dremin** [comment] 2022-03-10 05:19
Closing as duplicate of #15 and #45

**Closed by dremin** 2022-03-10 05:19 UTC
