### ISSUE TITLE
windows vista theme for retrobar

### ISSUE THREAD

**Issue by juicyhilton** [dremin/RetroBar#69] opened 2021-08-31 19:31 UTC
it was always kind of weird to me that vista didnt have a theme, as it uses the same taskbar system as 95-xp.

**Comment by Splitwirez** [comment] 2021-09-04 19:46
@juicyhilton Last I checked, @dremin did want it to happen, so it's likely less a matter of "if" and more of "when".

**Comment by dremin** [comment] 2021-09-24 23:35
Duplicate of #15

**Closed by dremin** 2021-09-24 23:35 UTC
