### ISSUE TITLE
no merging icons / multiple virtual desktop support

### ISSUE THREAD

**Issue by Ant-28** [dremin/RetroBar#479] opened 2022-11-28 09:17 UTC
Is it possible to add an option to merge all icons from an executable (much like windows 7)? While this doesn't entirely match the aesthetic of Windows Vista and earlier, it would make apps look less cluttered, if many are open. 
Apps across multiple virtual desktops are shown on the taskbar. Is it possible to only show apps on the task bar for the virtual desktop they are in?

**Comment by dremin** [comment] 2023-04-27 23:54
Windows 7 style is duplicate of #45 

Virtual desktop support is duplicate of #131

**Closed by dremin** 2023-04-27 23:54 UTC
