### ISSUE TITLE
Some suggestion.......

### ISSUE THREAD

**Issue by SeeenW** [dremin/RetroBar#630] opened 2023-07-16 10:13 UTC
Im a _crazy_ vista fan so i try retrobar and it take a awsome effect!

Like this:
![}M{%MCYVSE~JPA$MLU R9YP](https://github.com/dremin/RetroBar/assets/121167543/a905fe93-df50-4516-b778-86f5e8ea1430)
 But i can't hide the network icon so i can' use network activity indicator, and i can't move the volume icon's position so my QQ (yeah im a chinese) is in a wrong place........
![image](https://github.com/dremin/RetroBar/assets/121167543/8bd5fe91-aeb1-4af8-aa28-1bc32df9ab4a)

![image](https://github.com/dremin/RetroBar/assets/121167543/d7686b80-0335-4eda-a681-32d213a8b09c)

thank you!

**Comment by dremin** [comment] 2023-07-22 20:23
RetroBar doesn't currently have support for fully hiding a notification icon, however, you can enable the "collapse notification area icons" setting, and set the default network icon to "hide when inactive" and the network activity indicator icon to "always show". That way, the default one is always hidden under the collapsed area.

To re-order your icons, you can achieve this affect also by using the "always show" setting on the volume icon. Basically, whenever you change the setting, that icon goes to the right-most position. So you can effectively re-order icons by toggling the setting.

Hope this helps!

**Comment by dremin** [comment] 2024-04-28 08:19
Closing as a duplicate of #338 which I am working on.

**Closed by dremin** 2024-04-28 08:19 UTC
