### ISSUE TITLE
Retrobar causes explorer.exe crashing and restarts over and over after u restart explorer.exe! (11 24H2)

### ISSUE THREAD

**Issue by RedDragonTix** [dremin/RetroBar#927] opened 2024-10-16 08:53 UTC
When u try to restart explorer.exe with retrobar running, it causes crashes and flashes but when u close retrobar.exe, nothing happens!

**Comment by tamarindojuice** [comment] 2024-10-19 21:50
I can confirm, same behaviour here. 
Windows 11 24H2

**Comment by manaphychu** [comment] 2024-10-30 21:29
Me too

**Comment by dremin** [comment] 2024-11-21 07:01
Closing as duplicate of #457 (which will be fixed in the next version).

**Closed by dremin** 2024-11-21 07:01 UTC
