### ISSUE TITLE
turn off unnecessary icons in tray

### ISSUE THREAD

**Issue by exalye** [dremin/RetroBar#161] opened 2021-11-11 16:24 UTC
for example i dont need those icons, I can't turn them off in any way, please add the option to turn them off 
![image](https://user-images.githubusercontent.com/94129338/141332875-917b92bf-32bc-4af7-a6ef-001a8fe9ef38.png)

**Comment by exalye** [comment] 2021-11-11 16:27
or just make these icons look like they should look on XP

**Comment by SIX10** [comment] 2021-11-15 21:10
You could always just use the "hide notifications" option in RetroBar properties, which just groups them all into a submenu. If you want the icons changed, I think you can do some resourcehacker wizardry, but I also heard it broke a few Windows 10 updates ago.

**Comment by dremin** [comment] 2022-01-10 04:30
Closing as duplicate of #47

**Closed by dremin** 2022-01-10 04:30 UTC
