### ISSUE TITLE
Allow Two Or More Rows Please

### ISSUE THREAD

**Issue by ceeyee** [dremin/RetroBar#899] opened 2024-08-16 01:30 UTC
Current I couldn't find a way to increase the bar to two or more rows, which would be greatly desired because we often have a large number of quick launch icons and windows opened.

Thank you very much for your consideration.

**Comment by dremin** [comment] 2024-11-21 07:02
Closing as duplicate of #14 (which will be fixed in the next version).

**Closed by dremin** 2024-11-21 07:02 UTC
