### ISSUE TITLE
Add "Show the desktop" shortcut, and this annoying gap.

### ISSUE THREAD

**Issue by Saint4san** [dremin/RetroBar#173] opened 2021-11-22 03:17 UTC
**Add "Show the desktop" shortcut at the right corner of the taskbar...**
Well, it's a bit annoying not being able to do this quickly, and having to press Windows + D, or minimize one by one the tabs.

It would be great if this option was added, even if it's not like in the original system.

**And about the gap... it's simply despairing**
![image](https://user-images.githubusercontent.com/80080012/142795875-5324e9a4-e85f-4430-9754-b81eead89851.png)

I use windows 7 64 bits service pack 1, 1366x768 monitor.

**Comment by xoascf** [comment] 2021-11-22 03:46
As for the first issue, the Show desktop feature is currently in development (#169).

The second issue has been fixed recently (reported in #53 and #71, fixed with cairoshell/ManagedShell#41 in #162).

**Comment by ToruTheRedFox** [comment] 2021-12-23 11:34
I just use a quick launch shortcut

**Comment by dremin** [comment] 2022-07-19 01:48
Duplicate of #84

**Closed by dremin** 2022-07-19 01:48 UTC
