### ISSUE TITLE
[Request] Taskbar Size

### ISSUE THREAD

**Issue by SuperKirbylover** [dremin/RetroBar#135] opened 2021-10-26 17:33 UTC
i have a 4k monitor and as such the taskbar is... really really tiny compared to everything LMAO
for reference, the height of my taskbar without retrobar is 60px. retrobar is like 45px
would it be possible if, in the future, we could edit the size of the bar to make it more readable on bigger monitors?

**Comment by kwagraphics** [comment] 2021-12-01 04:56
Oh, yeah! Maybe some preset sizes to choose from. Simple as small, medium, large and maybe xtra large? or maybe not xtra large.

**Comment by dremin** [comment] 2022-03-10 05:22
Closing as duplicate of #14

**Closed by dremin** 2022-03-10 05:22 UTC
