### ISSUE TITLE
Win11 22H2 Hanging

### ISSUE THREAD

**Issue by TLCPlusPlus** [dremin/RetroBar#612] opened 2023-06-29 15:45 UTC
Every now and then, what I consider a crash loop, keeps happening. I dont know what causes it explicitly as it seems to happen out of the blue, but until its found out and fixed, I made a restart powershell script that forces the exe to force kill the process and start it back up.

Symptoms include:

- Unable to start up any other program or games.
- Desktop flashes black every 1-2 seconds.
- Not even task manager can save you, since it refuses to start (but if powershell is open, it can run the powershell script).
- Right clicking on Desktop shows 1-2 menu items that indefinitely say "Loading..." when it should be other items such as "Open in Terminal"

It immediately stops when Retrobar is force quit.

For those that are experiencing the same issue, heres my hotfix. It simply quits RetroBar and then starts it back up. Just run it once when symptoms show. I made it an alias too just for ease of access instead of constantly typing out the file path of the .ps1 file.

```
Stop-Process -Name RetroBar -Force
Write-Output "Stopping Process: Retrobar...2s"
Start-Sleep -Seconds 2
Start-Process -FilePath "FilePathTo\RetroBar.exe"
Write-Output "Restarting process...1s"
Start-Sleep -Seconds 1
Write-Output "Finished! Press any key to quit..."
[void][System.Console]::ReadKey($FALSE)
```

**Comment by dremin** [comment] 2023-07-22 20:25
Explorer has some trouble starting sometimes while RetroBar is already running. To me it sounds like Explorer is actually crashing but then because RetroBar is open, it can't restart. Do you see crash logs for Explorer in event viewer by chance when this is happening?

**Comment by TLCPlusPlus** [comment] 2023-07-26 21:14
> Explorer has some trouble starting sometimes while RetroBar is already running. To me it sounds like Explorer is actually crashing but then because RetroBar is open, it can't restart. Do you see crash logs for Explorer in event viewer by chance when this is happening?

No, the only thing I see is Kernal-Power:
"The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly."

Which is expected, because that was the only way I could force it if it couldnt even start powershell or run the above script. Usually I have Powershell just waiting in the background, but if I forget, thats plan B.

**Comment by p1ckaxe** [comment] 2023-07-29 05:50
Same issue here, Retrobar is the only thing to complete my Windows XP experience for 11 22H2. Sadly, not even older versions can run without Explorer Restarts.

**Comment by jdsuhlmann** [comment] 2023-09-04 12:01
works fine for me, guess it was patched

**Comment by dremin** [comment] 2024-12-02 01:08
Closing as duplicate of #457, which is fixed in the next version.

**Closed by dremin** 2024-12-02 01:08 UTC
