### ISSUE TITLE
Cannot move elements on the taskbar

### ISSUE THREAD

**Issue by Jonson26** [dremin/RetroBar#147] opened 2021-11-04 13:41 UTC
It seems to be impossible to change the position of tasks on the taskbar.

**Comment by kwagraphics** [comment] 2021-12-01 04:53
Yes! Maybe if we could unlock the taskbar we could move the system tray icons.

I really like this, but I like my system tray icons is a specific order. As well as my taskbar icons. Can't move them with it locked.

**Comment by dremin** [comment] 2022-01-12 05:08
Closing as duplicate of #19, which should be fixed in the next release.

**Closed by dremin** 2022-01-12 05:08 UTC
