### ISSUE TITLE
Suggestion: Windows 7 bar adding.

### ISSUE THREAD

**Issue by VeysellOZTURK** [dremin/RetroBar#832] opened 2024-05-08 10:03 UTC
If you add windows 7 bar its can be good I guess.

![AxYP2](https://github.com/dremin/RetroBar/assets/119420180/45008e2e-b00a-4d53-913d-b6d310099a31)

**Comment by AceDriver53** [comment] 2024-05-11 08:33
Yes it would be great if you guys added the Windows 7 Taskbar, with the color themes and transparency effect :D

**Comment by Polraudio** [comment] 2024-06-13 16:35
Yes please, that would be awesome. Even without the transparency it would be awesome.

**Comment by win-ini** [comment] 2024-07-01 07:21
it'd require a lot of refactoring of the code to add the superbar, I'm sure. Windows 7 had bigger icons on the taskbar by default than older versions, and just including the small taskbar mode isn't a really very good idea either. besides, Windows 7 isn't really very *retro*, at least not in my eyes.

**Comment by dremin** [comment] 2024-07-17 00:49
Duplicate of #45

**Closed by dremin** 2024-07-17 00:49 UTC
